## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Importing Dataset

In [3]:
dataset = pd.read_csv('./data/csv_experiments.csv')

In [4]:
dataset

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web03_00000  2019-04-27 22:38:47.691169   
1              1  zoo_web03_00001  2019-04-27 22:40:19.908876   
2              2  zoo_web03_00002  2019-04-27 22:41:48.337751   
3              3  zoo_web03_00003  2019-04-27 22:43:17.768555   
4              4  zoo_web03_00004  2019-04-27 22:44:48.990874   
...          ...              ...                         ...   
1595        1595  zoo_web03_01595  2019-04-29 14:21:09.295613   
1596        1596  zoo_web03_01596  2019-04-29 14:22:39.822087   
1597        1597  zoo_web03_01597  2019-04-29 14:24:10.093956   
1598        1598  zoo_web03_01598  2019-04-29 14:25:40.837528   
1599        1599  zoo_web03_01599  2019-04-29 14:27:10.006612   

                 experiment_stop  \
0     2019-04-27 22:39:49.979553   
1     2019-04-27 22:41:19.970489   
2     2019-04-27 22:42:48.399599   
3     2019-04-27 22:44:17.826881   
4     2019-04-27 22:45:49.049718   
...                          ...   
1595  2019-04-29 14:22:09.356730   
1596  2019-04-29 14:23:39.884027   
1597  2019-04-29 14:25:10.154101   
1598  2019-04-29 14:26:40.898468   
1599  2019-04-29 14:28:10.067019   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             39778.0   
1                                             39746.0   
2                                             39699.0   
3                                             39081.0   
4                                             39619.0   
...                                               ...   
1595                                             80.0   
1596                                             78.0   
1597                                             81.0   
1598                                             80.0   
1599                                             81.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             1.0   
1                                             1.0   
2                                             1.0   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                        /   
1                                        /   
2                                        /   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
... 

## Removing columns whose entire column is zero

In [5]:
def all_entries_nonzero(column):
    return (column != 0).any()

columns_to_drop = dataset.columns[~dataset.apply(all_entries_nonzero)]
dataset_new = dataset.drop(columns_to_drop, axis=1)


In [6]:
dataset_new

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web03_00000  2019-04-27 22:38:47.691169   
1              1  zoo_web03_00001  2019-04-27 22:40:19.908876   
2              2  zoo_web03_00002  2019-04-27 22:41:48.337751   
3              3  zoo_web03_00003  2019-04-27 22:43:17.768555   
4              4  zoo_web03_00004  2019-04-27 22:44:48.990874   
...          ...              ...                         ...   
1595        1595  zoo_web03_01595  2019-04-29 14:21:09.295613   
1596        1596  zoo_web03_01596  2019-04-29 14:22:39.822087   
1597        1597  zoo_web03_01597  2019-04-29 14:24:10.093956   
1598        1598  zoo_web03_01598  2019-04-29 14:25:40.837528   
1599        1599  zoo_web03_01599  2019-04-29 14:27:10.006612   

                 experiment_stop  \
0     2019-04-27 22:39:49.979553   
1     2019-04-27 22:41:19.970489   
2     2019-04-27 22:42:48.399599   
3     2019-04-27 22:44:17.826881   
4     2019-04-27 22:45:49.049718   
...                          ...   
1595  2019-04-29 14:22:09.356730   
1596  2019-04-29 14:23:39.884027   
1597  2019-04-29 14:25:10.154101   
1598  2019-04-29 14:26:40.898468   
1599  2019-04-29 14:28:10.067019   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             39778.0   
1                                             39746.0   
2                                             39699.0   
3                                             39081.0   
4                                             39619.0   
...                                               ...   
1595                                             80.0   
1596                                             78.0   
1597                                             81.0   
1598                                             80.0   
1599                                             81.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             1.0   
1                                             1.0   
2                                             1.0   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                        /   
1                                        /   
2                                        /   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
... 

# Checking for any Null values in dataset


In [7]:
dataset_new = dataset_new.replace('', np.nan)
dataset_new.isnull().sum()

Unnamed: 0                                           0
experiment_name                                      0
experiment_start                                     0
experiment_stop                                      0
metric__mp.input.vdu01.0__ab_completed_requests    102
                                                  ... 
param__mp__mp.output__address                        0
param__mp__mp.output__connection_point               0
param__mp__mp.output__container                      0
param__mp__mp.output__name                           0
run_id                                               0
Length: 77, dtype: int64

In [8]:
dataset_new = dataset_new.dropna(axis=1, how='all')
dataset_new.isnull().sum()

Unnamed: 0                                           0
experiment_name                                      0
experiment_start                                     0
experiment_stop                                      0
metric__mp.input.vdu01.0__ab_completed_requests    102
                                                  ... 
param__mp__mp.output__address                        0
param__mp__mp.output__connection_point               0
param__mp__mp.output__container                      0
param__mp__mp.output__name                           0
run_id                                               0
Length: 67, dtype: int64

In [9]:
dataset_new

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web03_00000  2019-04-27 22:38:47.691169   
1              1  zoo_web03_00001  2019-04-27 22:40:19.908876   
2              2  zoo_web03_00002  2019-04-27 22:41:48.337751   
3              3  zoo_web03_00003  2019-04-27 22:43:17.768555   
4              4  zoo_web03_00004  2019-04-27 22:44:48.990874   
...          ...              ...                         ...   
1595        1595  zoo_web03_01595  2019-04-29 14:21:09.295613   
1596        1596  zoo_web03_01596  2019-04-29 14:22:39.822087   
1597        1597  zoo_web03_01597  2019-04-29 14:24:10.093956   
1598        1598  zoo_web03_01598  2019-04-29 14:25:40.837528   
1599        1599  zoo_web03_01599  2019-04-29 14:27:10.006612   

                 experiment_stop  \
0     2019-04-27 22:39:49.979553   
1     2019-04-27 22:41:19.970489   
2     2019-04-27 22:42:48.399599   
3     2019-04-27 22:44:17.826881   
4     2019-04-27 22:45:49.049718   
...                          ...   
1595  2019-04-29 14:22:09.356730   
1596  2019-04-29 14:23:39.884027   
1597  2019-04-29 14:25:10.154101   
1598  2019-04-29 14:26:40.898468   
1599  2019-04-29 14:28:10.067019   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             39778.0   
1                                             39746.0   
2                                             39699.0   
3                                             39081.0   
4                                             39619.0   
...                                               ...   
1595                                             80.0   
1596                                             78.0   
1597                                             81.0   
1598                                             80.0   
1599                                             81.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             1.0   
1                                             1.0   
2                                             1.0   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                        /   
1                                        /   
2                                        /   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
... 

In [10]:
def all_values_same(column):
    return column.nunique() == 1

columns_to_drop = dataset_new.columns[dataset_new.apply(all_values_same)]
dataset_new = dataset_new.drop(columns_to_drop, axis=1)

In [11]:
dataset_new.isnull().sum()

Unnamed: 0                                                       0
experiment_name                                                  0
experiment_start                                                 0
experiment_stop                                                  0
metric__mp.input.vdu01.0__ab_completed_requests                102
metric__mp.input.vdu01.0__ab_doc_length                        102
metric__mp.input.vdu01.0__ab_doc_path                          102
metric__mp.input.vdu01.0__ab_failed_requests                   102
metric__mp.input.vdu01.0__ab_html_transfer_byte                102
metric__mp.input.vdu01.0__ab_mean_time_per_request             102
metric__mp.input.vdu01.0__ab_request_per_second                102
metric__mp.input.vdu01.0__ab_rt_percentiles_csv                102
metric__mp.input.vdu01.0__ab_srv_version                       102
metric__mp.input.vdu01.0__ab_time_used_s                       102
metric__mp.input.vdu01.0__ab_total_transfer_byte              

In [12]:
dataset_new = dataset_new.dropna()

In [13]:
dataset_new.isnull().sum()

Unnamed: 0                                                     0
experiment_name                                                0
experiment_start                                               0
experiment_stop                                                0
metric__mp.input.vdu01.0__ab_completed_requests                0
metric__mp.input.vdu01.0__ab_doc_length                        0
metric__mp.input.vdu01.0__ab_doc_path                          0
metric__mp.input.vdu01.0__ab_failed_requests                   0
metric__mp.input.vdu01.0__ab_html_transfer_byte                0
metric__mp.input.vdu01.0__ab_mean_time_per_request             0
metric__mp.input.vdu01.0__ab_request_per_second                0
metric__mp.input.vdu01.0__ab_rt_percentiles_csv                0
metric__mp.input.vdu01.0__ab_srv_version                       0
metric__mp.input.vdu01.0__ab_time_used_s                       0
metric__mp.input.vdu01.0__ab_total_transfer_byte               0
metric__mp.input.vdu01.0_

In [14]:
dataset_new.columns

Index(['Unnamed: 0', 'experiment_name', 'experiment_start', 'experiment_stop',
       'metric__mp.input.vdu01.0__ab_completed_requests',
       'metric__mp.input.vdu01.0__ab_doc_length',
       'metric__mp.input.vdu01.0__ab_doc_path',
       'metric__mp.input.vdu01.0__ab_failed_requests',
       'metric__mp.input.vdu01.0__ab_html_transfer_byte',
       'metric__mp.input.vdu01.0__ab_mean_time_per_request',
       'metric__mp.input.vdu01.0__ab_request_per_second',
       'metric__mp.input.vdu01.0__ab_rt_percentiles_csv',
       'metric__mp.input.vdu01.0__ab_srv_version',
       'metric__mp.input.vdu01.0__ab_time_used_s',
       'metric__mp.input.vdu01.0__ab_total_transfer_byte',
       'metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metr

In [15]:
dataset_new = dataset_new.drop(['Unnamed: 0','experiment_name', 'experiment_start', 'experiment_stop', 'metric__mp.input.vdu01.0__ab_doc_path', 'metric__mp.input.vdu01.0__ab_rt_percentiles_csv', 'metric__mp.input.vdu01.0__ab_srv_version', 'param__func__mp.input__cmd_start', 'param__header__all__config_id', 'param__header__all__repetition', 'run_id'],axis=1)
dataset_new.columns

Index(['metric__mp.input.vdu01.0__ab_completed_requests',
       'metric__mp.input.vdu01.0__ab_doc_length',
       'metric__mp.input.vdu01.0__ab_failed_requests',
       'metric__mp.input.vdu01.0__ab_html_transfer_byte',
       'metric__mp.input.vdu01.0__ab_mean_time_per_request',
       'metric__mp.input.vdu01.0__ab_request_per_second',
       'metric__mp.input.vdu01.0__ab_time_used_s',
       'metric__mp.input.vdu01.0__ab_total_transfer_byte',
       'metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__rx_bytes',
       'metric__mp.output.vdu01.0__stat__data__rx_packets',
       'metric

In [16]:
dataset_new.dtypes

metric__mp.input.vdu01.0__ab_completed_requests                float64
metric__mp.input.vdu01.0__ab_doc_length                        float64
metric__mp.input.vdu01.0__ab_failed_requests                   float64
metric__mp.input.vdu01.0__ab_html_transfer_byte                float64
metric__mp.input.vdu01.0__ab_mean_time_per_request             float64
metric__mp.input.vdu01.0__ab_request_per_second                float64
metric__mp.input.vdu01.0__ab_time_used_s                       float64
metric__mp.input.vdu01.0__ab_total_transfer_byte               float64
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    float64
metric__mp.input.vdu01.0__stat__data__rx_bytes                 float64
metric__mp.input.vdu01.0__stat__data__rx_packets               float64
metric__mp.input.vdu01.0__stat__data__tx_bytes                 float64
metric__mp.input.vdu01.0__stat__data__tx_packets               float64
metric__mp.input.vdu01.0__stat__eth0__rx_bytes                 float64
metric

In [17]:
X = dataset_new.iloc[:, :-2].values
y = dataset_new.iloc[:, -2:].values

In [18]:
print(y)

[[1.00e-01 6.40e+01]
 [1.00e-01 6.40e+01]
 [1.00e-01 6.40e+01]
 ...
 [1.00e+00 5.12e+02]
 [1.00e+00 5.12e+02]
 [1.00e+00 5.12e+02]]


## One Hot Encoding mem_max variable

In [19]:
data = dataset_new['param__func__de.upb.px-squid.0.1__mem_max']
encoded_data = pd.get_dummies(data, columns=['param__func__de.upb.px-squid.0.1__mem_max'])
dataset_new = dataset_new.drop('param__func__de.upb.px-squid.0.1__mem_max', axis = 1)
dataset_new = pd.concat([dataset_new, encoded_data], axis=1)
dataset_new

metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             39778.0   
1                                             39746.0   
2                                             39699.0   
3                                             39081.0   
4                                             39619.0   
...                                               ...   
1595                                             80.0   
1596                                             78.0   
1597                                             81.0   
1598                                             80.0   
1599                                             81.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
...                                            ...   
1595                                           0.0   
1596                                           0.0   
1597                                           0.0   
1598                                           0.0   
1599                                           0.0   

      metric__mp.input.vdu01.0__ab_html_transfer_byte  \
0                                        0.000000e+00   
1                                        0.000000e+00   
2                                        0.000000e+00   
3                                        0.000000e+00   
4                                        0.000000e+00   
...                                               ...   
1595                                     2.547109e+10   
1596                                     2.483431e+10   
1597                                     2.578948e+10   
1598                                     2.547109e+10   
1599                                     2.578948e+10   

      metric__mp.input.vdu01.0__ab_mean_time_per_request  \
0                                                 1.530    
1                                                 1.522    
2                                                 1.513    
3                                                 1.552    
4                                                 1.525    
...                                                 ...    
1595                                            751.799    
1596                                            770.006    
1597                                            745.009    
1598                                            757.509    
1599                                            748.802    

      metric__mp.input.vdu01.0__ab_request_per_second  \
0                                              653.76   
1                                              657.14   
2                                              660.99   
3                                              644.47   
4                                              655.77   
...                                               ...   
1595                                             1.33   
1596                                             1.30   
1597                                             1.34   
1598                                             1.32   
1599                                             1

In [20]:
y= dataset_new.iloc[:, -5:].values
print(y)

[[0.1 1.  0.  0.  0. ]
 [0.1 1.  0.  0.  0. ]
 [0.1 1.  0.  0.  0. ]
 ...
 [1.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  1. ]]


## Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Separate the two output features
y_train_output1 = y_train[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_train_output2 = y_train[:, -4]  # Second column for binary classification

y_train_output3 = y_train[:, -3]
y_train_output4 = y_train[:, -2]
y_train_output5 = y_train[:, -1]

y_test_output1 = y_test[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_test_output2 = y_test[:, -4]  # Second column for binary classification

y_test_output3 = y_test[:, -3]
y_test_output4 = y_test[:, -2]
y_test_output5 = y_test[:, -1]

In [22]:
print(y_train_output1)

[0.5 0.1 0.6 ... 0.9 0.5 0.5]


## Feature Scaling

In [23]:
from sklearn.preprocessing import MinMaxScaler

# Normalize input features
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)



In [24]:
print(X_train_normalized)

[[6.96607296e-01 0.00000000e+00 0.00000000e+00 ... 4.80969670e-01
  6.94689103e-01 6.89103031e-01]
 [1.10395602e-01 0.00000000e+00 0.00000000e+00 ... 1.03877539e-02
  1.04636491e-01 8.78564625e-02]
 [8.61267984e-01 0.00000000e+00 0.00000000e+00 ... 6.13151537e-01
  8.60434184e-01 8.58008852e-01]
 ...
 [1.90234443e-04 1.00000000e+00 0.00000000e+00 ... 8.22671525e-01
  6.83282924e-02 2.69146731e-01]
 [9.36975613e-05 1.00000000e+00 0.00000000e+00 ... 4.00114884e-01
  3.16517869e-02 1.24869741e-01]
 [9.36975613e-05 1.00000000e+00 0.00000000e+00 ... 4.28263548e-01
  5.40173883e-02 2.14437784e-01]]


In [25]:
print(type(y_train_output1))
print(type(y_train_output2))
print(type(y_train_output3))
print(type(y_train_output4))
print(type(y_train_output5))

print(type(y_test_output1))
print(type(y_test_output2))
print(type(y_test_output3))
print(type(y_test_output4))
print(type(y_test_output5))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [26]:
print(X_train_normalized.shape)
print(y_train_output1.shape)
print(y_train_output2.shape)
print(y_train_output3.shape)
print(y_train_output4.shape)
print(y_train_output5.shape)

print(y_test_output1.shape)
print(y_test_output2.shape)
print(y_test_output3.shape)
print(y_test_output4.shape)
print(y_test_output5.shape)

(1198, 33)
(1198,)
(1198,)
(1198,)
(1198,)
(1198,)
(300,)
(300,)
(300,)
(300,)
(300,)


## Building Model

In [27]:
input_shape = (33,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=64, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dense(units=32, activation='relu')(x)
output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification

output_3 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_3')(x)  # Output 2: Classification
output_4 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_4')(x)  # Output 2: Classification
output_5 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_5')(x)  # Output 2: Classification

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2, output_3, output_4, output_5])

# Check the model output names
print("Model Output Names:", model.output_names)  


Model Output Names: ['output_1', 'output_2', 'output_3', 'output_4', 'output_5']


In [28]:
model.compile(
    loss={
        'output_1': 'mean_squared_error',  # Regression loss function
        'output_2': 'binary_crossentropy',  # Categorical classification loss function
        'output_3': 'binary_crossentropy',
        'output_4': 'binary_crossentropy',
        'output_5': 'binary_crossentropy',
    },
    optimizer='adam',
    metrics={
        'output_1': ['mae', 'mse'],
        'output_2': 'accuracy',
        'output_3': 'accuracy',
        'output_4': 'accuracy',
        'output_5': 'accuracy',
    }
)

model.fit(X_train_normalized, {'output_1': y_train_output1, 'output_2': y_train_output2, 'output_3': y_train_output3, 'output_4': y_train_output4, 'output_5': y_train_output5},
          validation_data=(X_test_normalized, {'output_1': y_test_output1, 'output_2': y_test_output2, 'output_3': y_test_output3, 'output_4': y_test_output4, 'output_5': y_test_output5}),
          epochs=50, batch_size=32)



Epoch 1/50
38/38 [==============================] - 4s 40ms/step - loss: 2.6016 - output_1_loss: 0.0865 - output_2_loss: 0.6099 - output_3_loss: 0.6664 - output_4_loss: 0.6364 - output_5_loss: 0.6025 - output_1_mae: 0.2171 - output_1_mse: 0.0865 - output_2_accuracy: 0.7245 - output_3_accuracy: 0.5492 - output_4_accuracy: 0.6561 - output_5_accuracy: 0.7304 - val_loss: 2.2888 - val_output_1_loss: 0.0197 - val_output_2_loss: 0.5312 - val_output_3_loss: 0.6104 - val_output_4_loss: 0.5826 - val_output_5_loss: 0.5450 - val_output_1_mae: 0.1073 - val_output_1_mse: 0.0197 - val_output_2_accuracy: 0.7767 - val_output_3_accuracy: 0.7200 - val_output_4_accuracy: 0.7400 - val_output_5_accuracy: 0.7633
Epoch 2/50
38/38 [==============================] - 0s 9ms/step - loss: 2.3018 - output_1_loss: 0.0185 - output_2_loss: 0.5775 - output_3_loss: 0.5661 - output_4_loss: 0.5602 - output_5_loss: 0.5795 - output_1_mae: 0.1068 - output_1_mse: 0.0185 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579 

Epoch 13/50
38/38 [==============================] - 0s 9ms/step - loss: 2.2568 - output_1_loss: 0.0084 - output_2_loss: 0.5693 - output_3_loss: 0.5540 - output_4_loss: 0.5549 - output_5_loss: 0.5703 - output_1_mae: 0.0679 - output_1_mse: 0.0084 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579 - output_4_accuracy: 0.7588 - output_5_accuracy: 0.7437 - val_loss: 2.2669 - val_output_1_loss: 0.0069 - val_output_2_loss: 0.5327 - val_output_3_loss: 0.6015 - val_output_4_loss: 0.5749 - val_output_5_loss: 0.5509 - val_output_1_mae: 0.0595 - val_output_1_mse: 0.0069 - val_output_2_accuracy: 0.7767 - val_output_3_accuracy: 0.7200 - val_output_4_accuracy: 0.7400 - val_output_5_accuracy: 0.7633
Epoch 14/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2532 - output_1_loss: 0.0086 - output_2_loss: 0.5696 - output_3_loss: 0.5516 - output_4_loss: 0.5551 - output_5_loss: 0.5684 - output_1_mae: 0.0689 - output_1_mse: 0.0086 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579

Epoch 25/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2343 - output_1_loss: 0.0076 - output_2_loss: 0.5583 - output_3_loss: 0.5471 - output_4_loss: 0.5538 - output_5_loss: 0.5674 - output_1_mae: 0.0654 - output_1_mse: 0.0076 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579 - output_4_accuracy: 0.7588 - output_5_accuracy: 0.7437 - val_loss: 2.2676 - val_output_1_loss: 0.0070 - val_output_2_loss: 0.5350 - val_output_3_loss: 0.5961 - val_output_4_loss: 0.5759 - val_output_5_loss: 0.5536 - val_output_1_mae: 0.0499 - val_output_1_mse: 0.0070 - val_output_2_accuracy: 0.7767 - val_output_3_accuracy: 0.7200 - val_output_4_accuracy: 0.7400 - val_output_5_accuracy: 0.7633
Epoch 26/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2376 - output_1_loss: 0.0076 - output_2_loss: 0.5636 - output_3_loss: 0.5509 - output_4_loss: 0.5498 - output_5_loss: 0.5657 - output_1_mae: 0.0661 - output_1_mse: 0.0076 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579

Epoch 37/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2184 - output_1_loss: 0.0081 - output_2_loss: 0.5564 - output_3_loss: 0.5472 - output_4_loss: 0.5467 - output_5_loss: 0.5600 - output_1_mae: 0.0690 - output_1_mse: 0.0081 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579 - output_4_accuracy: 0.7588 - output_5_accuracy: 0.7462 - val_loss: 2.2764 - val_output_1_loss: 0.0056 - val_output_2_loss: 0.5392 - val_output_3_loss: 0.6021 - val_output_4_loss: 0.5787 - val_output_5_loss: 0.5508 - val_output_1_mae: 0.0468 - val_output_1_mse: 0.0056 - val_output_2_accuracy: 0.7800 - val_output_3_accuracy: 0.7200 - val_output_4_accuracy: 0.7400 - val_output_5_accuracy: 0.7633
Epoch 38/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2132 - output_1_loss: 0.0071 - output_2_loss: 0.5537 - output_3_loss: 0.5469 - output_4_loss: 0.5452 - output_5_loss: 0.5603 - output_1_mae: 0.0625 - output_1_mse: 0.0071 - output_2_accuracy: 0.7404 - output_3_accuracy: 0.7579

Epoch 49/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2081 - output_1_loss: 0.0066 - output_2_loss: 0.5526 - output_3_loss: 0.5466 - output_4_loss: 0.5484 - output_5_loss: 0.5539 - output_1_mae: 0.0600 - output_1_mse: 0.0066 - output_2_accuracy: 0.7396 - output_3_accuracy: 0.7579 - output_4_accuracy: 0.7588 - output_5_accuracy: 0.7421 - val_loss: 2.2797 - val_output_1_loss: 0.0081 - val_output_2_loss: 0.5454 - val_output_3_loss: 0.6007 - val_output_4_loss: 0.5795 - val_output_5_loss: 0.5460 - val_output_1_mae: 0.0569 - val_output_1_mse: 0.0081 - val_output_2_accuracy: 0.7767 - val_output_3_accuracy: 0.7200 - val_output_4_accuracy: 0.7400 - val_output_5_accuracy: 0.7600
Epoch 50/50
38/38 [==============================] - 0s 8ms/step - loss: 2.2020 - output_1_loss: 0.0075 - output_2_loss: 0.5496 - output_3_loss: 0.5461 - output_4_loss: 0.5471 - output_5_loss: 0.5517 - output_1_mae: 0.0645 - output_1_mse: 0.0075 - output_2_accuracy: 0.7454 - output_3_accuracy: 0.7579

In [29]:
# After the model is trained, you can make predictions
y_pred_output1, y_pred_output2, y_pred_output3, y_pred_output4, y_pred_output5 = model.predict(X_test_normalized)

# For output_1 (Regression)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_output1 = mean_absolute_error(y_test_output1, y_pred_output1)
mse_output1 = mean_squared_error(y_test_output1, y_pred_output1)
r2_output1 = r2_score(y_test_output1, y_pred_output1)

print("Output 1 - Mean Absolute Error:", mae_output1)
print("Output 1 - Mean Squared Error:", mse_output1)
print("Output 1 - R^2 Score:", r2_output1)

# For output_2 to output_5 (Classification)
from sklearn.metrics import accuracy_score, confusion_matrix

for i in range(4):
    cm = confusion_matrix(y_test_output2, np.round(y_pred_output2))
    accuracy = accuracy_score(y_test_output2, np.round(y_pred_output2))
    print(f"Confusion Matrix for Classification Output {i+2}:\n{cm}")
    print(f"Accuracy Score for Classification Output {i+2}: {accuracy}")




10/10 [==============================] - 0s 3ms/step
Output 1 - Mean Absolute Error: 0.0642845814228058
Output 1 - Mean Squared Error: 0.008069606240640237
Output 1 - R^2 Score: 0.8951847941033885
Confusion Matrix for Classification Output 2:
[[232   1]
 [ 66   1]]
Accuracy Score for Classification Output 2: 0.7766666666666666
Confusion Matrix for Classification Output 3:
[[232   1]
 [ 66   1]]
Accuracy Score for Classification Output 3: 0.7766666666666666
Confusion Matrix for Classification Output 4:
[[232   1]
 [ 66   1]]
Accuracy Score for Classification Output 4: 0.7766666666666666
Confusion Matrix for Classification Output 5:
[[232   1]
 [ 66   1]]
Accuracy Score for Classification Output 5: 0.7766666666666666


In [30]:
y_test1 = y_test[:,0]

rounded_y_pred = y_pred_output1.reshape(len(y_pred_output1), 1).round(1)

# Reshape y_test1 to a column vector
y_test1_reshaped = y_test1.reshape(len(y_test1), 1)

# Concatenate both arrays side by side (along axis 1)
result = np.concatenate((rounded_y_pred, y_test1_reshaped), axis=1)
np.set_printoptions(precision=1)
print(result)

[[0.8 0.9]
 [0.1 0.1]
 [0.8 0.9]
 [0.8 0.9]
 [0.3 0.3]
 [0.9 1. ]
 [0.2 0.2]
 [0.7 0.7]
 [0.3 0.3]
 [0.8 0.8]
 [0.7 1. ]
 [0.6 0.6]
 [0.1 0.1]
 [0.8 1. ]
 [0.8 0.9]
 [0.2 0.2]
 [0.6 0.6]
 [0.7 0.8]
 [0.3 0.3]
 [0.4 0.4]
 [0.7 0.8]
 [0.5 0.5]
 [0.8 0.7]
 [0.6 0.7]
 [0.8 0.9]
 [0.7 0.8]
 [0.8 0.8]
 [0.2 0.2]
 [0.  0.1]
 [0.7 0.6]
 [0.6 0.5]
 [0.5 0.5]
 [0.9 1. ]
 [0.2 0.2]
 [0.7 0.9]
 [0.2 0.2]
 [0.7 0.7]
 [0.4 0.4]
 [0.8 0.8]
 [0.2 0.2]
 [0.4 0.4]
 [0.7 0.8]
 [0.6 0.7]
 [0.7 0.8]
 [0.8 0.8]
 [0.3 0.3]
 [0.2 0.2]
 [0.4 0.4]
 [0.7 0.8]
 [0.7 0.9]
 [0.7 0.8]
 [0.4 0.5]
 [0.2 0.2]
 [0.8 0.7]
 [0.3 0.3]
 [0.4 0.5]
 [0.5 0.5]
 [0.4 0.4]
 [0.6 0.7]
 [0.2 0.3]
 [0.7 0.8]
 [0.7 0.8]
 [0.8 0.9]
 [0.3 0.4]
 [0.1 0.1]
 [0.8 0.9]
 [0.4 0.4]
 [0.7 0.8]
 [0.5 0.5]
 [0.9 1. ]
 [0.7 0.8]
 [0.3 0.3]
 [0.5 0.6]
 [0.7 0.9]
 [0.4 0.4]
 [0.5 0.5]
 [0.5 0.5]
 [0.2 0.3]
 [0.5 0.6]
 [0.4 0.4]
 [0.6 0.6]
 [0.5 0.6]
 [0.8 0.7]
 [0.8 0.8]
 [0.7 0.7]
 [0.7 0.8]
 [0.3 0.3]
 [0.3 0.3]
 [0.8 0.8]
 [0.4 0.4]
 [0.1 0.1]

## K-fold Cross Validation

In [31]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

num_folds = 5

# Initialize lists to store the evaluation metrics for each fold
mse_output1_list = []
accuracy_output2_list = []
accuracy_output3_list = []
accuracy_output4_list = []
accuracy_output5_list = []

# Create the KFold object
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)


# Create the model
input_shape = (33,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=256, activation='relu')(inputs)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation
   

output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification
output_3 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_3')(x)
output_4 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_4')(x)
output_5 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_5')(x)

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2, output_3, output_4, output_5])

# Perform 5-fold cross-validation
for fold, (train_indices, val_indices) in enumerate(kfold.split(X_train_normalized)):
    print(f"Fold {fold+1}/{num_folds}")
    
    # Split the data into training and validation sets for this fold
    X_train_fold = X_train_normalized[train_indices]
    X_val_fold = X_train_normalized[val_indices]
    y_train_output1_fold = y_train_output1[train_indices]
    y_train_output2_fold = y_train_output2[train_indices]
    y_train_output3_fold = y_train_output3[train_indices]
    y_train_output4_fold = y_train_output4[train_indices]
    y_train_output5_fold = y_train_output5[train_indices]
    
    y_val_output1_fold = y_train_output1[val_indices]
    y_val_output2_fold = y_train_output2[val_indices]
    y_val_output3_fold = y_train_output3[val_indices]
    y_val_output4_fold = y_train_output4[val_indices]
    y_val_output5_fold = y_train_output5[val_indices]
    
    
    # Compile the model
    model.compile(
        loss={
            'output_1': 'mean_squared_error',  # Regression loss function
            'output_2': 'binary_crossentropy',  # classification loss function
            'output_3': 'binary_crossentropy',
            'output_4': 'binary_crossentropy',
            'output_5': 'binary_crossentropy',
        },
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        metrics={
            'output_1': ['mae', 'mse'],
            'output_2': 'accuracy',
            'output_3': 'accuracy',
            'output_4': 'accuracy',
            'output_5': 'accuracy',
        }
    )
    

    # Train the model
    model.fit(X_train_fold, {'output_1': y_train_output1_fold, 'output_2': y_train_output2_fold, 'output_3': y_train_output3_fold, 'output_4': y_train_output4_fold, 'output_5': y_train_output5_fold},
          epochs=100, batch_size=32, verbose=0)

    
    # Evaluate the model on validation data for this fold
    results = model.evaluate(X_val_fold, {'output_1': y_val_output1_fold, 'output_2': y_val_output2_fold, 'output_3': y_val_output3_fold, 'output_4': y_val_output4_fold, 'output_5': y_val_output5_fold})
#     print("Results:", results)
    
    mse_output1_list.append(results[2])  # Index 2 corresponds to MSE for 'output_1'
    accuracy_output2_list.append(results[8])  # Index 5 corresponds to accuracy for 'output_2'
    accuracy_output3_list.append(results[9])  # Index 8 corresponds to accuracy for 'output_3'
    accuracy_output4_list.append(results[10])  # Index 11 corresponds to accuracy for 'output_4'
    accuracy_output5_list.append(results[11])  # Index 14 corresponds to accuracy for 'output_5'




Fold 1/5
8/8 [==============================] - 1s 7ms/step - loss: 2.7604 - output_1_loss: 0.0076 - output_2_loss: 0.6681 - output_3_loss: 0.6418 - output_4_loss: 0.6882 - output_5_loss: 0.7548 - output_1_mae: 0.0665 - output_1_mse: 0.0076 - output_2_accuracy: 0.7083 - output_3_accuracy: 0.7375 - output_4_accuracy: 0.7000 - output_5_accuracy: 0.7875
Fold 2/5
8/8 [==============================] - 1s 7ms/step - loss: 4.4258 - output_1_loss: 0.0068 - output_2_loss: 1.0674 - output_3_loss: 1.2341 - output_4_loss: 1.2382 - output_5_loss: 0.8793 - output_1_mae: 0.0645 - output_1_mse: 0.0068 - output_2_accuracy: 0.6792 - output_3_accuracy: 0.6458 - output_4_accuracy: 0.6958 - output_5_accuracy: 0.7625
Fold 3/5
8/8 [==============================] - 1s 6ms/step - loss: 3.4418 - output_1_loss: 0.0084 - output_2_loss: 0.7885 - output_3_loss: 0.9317 - output_4_loss: 0.9752 - output_5_loss: 0.7380 - output_1_mae: 0.0703 - output_1_mse: 0.0084 - output_2_accuracy: 0.7667 - output_3_accuracy: 0.70

In [32]:
# Calculate the mean and standard deviation of evaluation metrics across all folds
mean_mse_output1 = np.mean(mse_output1_list)
mean_accuracy_output2 = np.mean(accuracy_output2_list)
mean_accuracy_output3 = np.mean(accuracy_output3_list)
mean_accuracy_output4 = np.mean(accuracy_output4_list)
mean_accuracy_output5 = np.mean(accuracy_output5_list)


std_mse_output1 = np.std(mse_output1_list)
std_accuracy_output2 = np.std(accuracy_output2_list)
std_accuracy_output3 = np.std(accuracy_output3_list)
std_accuracy_output4 = np.std(accuracy_output4_list)
std_accuracy_output5 = np.std(accuracy_output5_list)

# For regression task (output_1) - Calculate R-squared (R^2) score
y_true_output1 = np.concatenate([y_train_output1, y_test_output1])
y_pred_output1 = model.predict(np.concatenate([X_train_normalized, X_test_normalized]))[0]
r2_output1 = r2_score(y_true_output1, y_pred_output1)

print("Mean MSE (Output 1):", mean_mse_output1)
print("Mean Accuracy (Output 2):", mean_accuracy_output2)
print("Mean Accuracy (Output 3):", mean_accuracy_output3)
print("Mean Accuracy (Output 4):", mean_accuracy_output4)
print("Mean Accuracy (Output 5):", mean_accuracy_output5)

print("Standard Deviation MSE (Output 1):", std_mse_output1)
print("Standard Deviation Accuracy (Output 2):", std_accuracy_output2)
print("Standard Deviation Accuracy (Output 3):", std_accuracy_output3)
print("Standard Deviation Accuracy (Output 4):", std_accuracy_output4)
print("Standard Deviation Accuracy (Output 5):", std_accuracy_output5)

print("R^2 Score (Output 1 - Regression):", r2_output1)


47/47 [==============================] - 1s 4ms/step
Mean MSE (Output 1): 0.772468090057373
Mean Accuracy (Output 2): 0.7454776763916016
Mean Accuracy (Output 3): 0.7346513152122498
Mean Accuracy (Output 4): 0.7496827006340027
Mean Accuracy (Output 5): 0.784668755531311
Standard Deviation MSE (Output 1): 0.15749115925791496
Standard Deviation Accuracy (Output 2): 0.04509971209051864
Standard Deviation Accuracy (Output 3): 0.05559464495116321
Standard Deviation Accuracy (Output 4): 0.05065562481104102
Standard Deviation Accuracy (Output 5): 0.016247408620988883
R^2 Score (Output 1 - Regression): 0.9368619288224979


In [33]:
# 1. Compare Regression Output with Original Test Values

# Predict using the trained model on the test data for the regression output (output_1)
y_pred_output1_test = model.predict(X_test_normalized)[0]

# Reshape the predictions and original test values to match for comparison
y_pred_output1_test = y_pred_output1_test.flatten()

# Convert both arrays to the same data type (e.g., float64) for comparison
y_test_output1 = y_test_output1.astype(np.float64)
y_pred_output1_test = y_pred_output1_test.astype(np.float64)

# Stack the original test values and predicted values horizontally
comparison_output1 = np.column_stack((y_test_output1, y_pred_output1_test))

# Print the original test values and predicted values side by side
print("Original Test Values (Output 1) vs. Predicted Values (Output 1):")
print(comparison_output1)

10/10 [==============================] - 0s 3ms/step
Original Test Values (Output 1) vs. Predicted Values (Output 1):
[[0.9 0.9]
 [0.1 0.1]
 [0.9 0.8]
 [0.9 0.9]
 [0.3 0.3]
 [1.  1. ]
 [0.2 0.3]
 [0.7 0.8]
 [0.3 0.2]
 [0.8 1. ]
 [1.  0.9]
 [0.6 0.7]
 [0.1 0.2]
 [1.  0.9]
 [0.9 0.9]
 [0.2 0.2]
 [0.6 0.6]
 [0.8 0.8]
 [0.3 0.4]
 [0.4 0.5]
 [0.8 0.8]
 [0.5 0.5]
 [0.7 0.9]
 [0.7 0.7]
 [0.9 1. ]
 [0.8 0.7]
 [0.8 0.8]
 [0.2 0.2]
 [0.1 0.1]
 [0.6 0.6]
 [0.5 0.5]
 [0.5 0.4]
 [1.  0.9]
 [0.2 0.1]
 [0.9 0.8]
 [0.2 0.4]
 [0.7 0.8]
 [0.4 0.4]
 [0.8 0.8]
 [0.2 0.2]
 [0.4 0.5]
 [0.8 0.7]
 [0.7 0.7]
 [0.8 0.9]
 [0.8 0.8]
 [0.3 0.3]
 [0.2 0.2]
 [0.4 0.5]
 [0.8 0.7]
 [0.9 0.7]
 [0.8 0.9]
 [0.5 0.5]
 [0.2 0.3]
 [0.7 0.8]
 [0.3 0.4]
 [0.5 0.5]
 [0.5 0.4]
 [0.4 0.4]
 [0.7 0.8]
 [0.3 0.3]
 [0.8 0.9]
 [0.8 0.9]
 [0.9 1. ]
 [0.4 0.4]
 [0.1 0.2]
 [0.9 0.9]
 [0.4 0.4]
 [0.8 0.9]
 [0.5 0.4]
 [1.  1.2]
 [0.8 0.8]
 [0.3 0.3]
 [0.6 0.6]
 [0.9 0.9]
 [0.4 0.4]
 [0.5 0.4]
 [0.5 0.6]
 [0.3 0.3]
 [0.6 0.6]
 [0.4 0.4]
 [

In [34]:
# 2. Generate Confusion Matrix for Classification

# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output2_test = model.predict(X_test_normalized)[1]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output2_test_binary = np.round(y_pred_output2_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output2 = confusion_matrix(y_test_output2, y_pred_output2_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 2 - Classification):")
print(conf_matrix_output2)

10/10 [==============================] - 0s 2ms/step
Confusion Matrix (Output 2 - Classification):
[[179  54]
 [ 43  24]]


In [35]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output3_test = model.predict(X_test_normalized)[2]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output3_test_binary = np.round(y_pred_output3_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output3 = confusion_matrix(y_test_output3, y_pred_output3_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 3 - Classification):")
print(conf_matrix_output3)

10/10 [==============================] - 0s 4ms/step
Confusion Matrix (Output 3 - Classification):
[[169  47]
 [ 69  15]]


In [36]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output4_test = model.predict(X_test_normalized)[3]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output4_test_binary = np.round(y_pred_output4_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output4 = confusion_matrix(y_test_output4, y_pred_output4_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 4 - Classification):")
print(conf_matrix_output4)

10/10 [==============================] - 0s 3ms/step
Confusion Matrix (Output 4 - Classification):
[[167  55]
 [ 56  22]]


In [37]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output5_test = model.predict(X_test_normalized)[4]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output5_test_binary = np.round(y_pred_output5_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output5 = confusion_matrix(y_test_output5, y_pred_output5_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 5 - Classification):")
print(conf_matrix_output5)

10/10 [==============================] - 0s 3ms/step
Confusion Matrix (Output 5 - Classification):
[[193  36]
 [ 51  20]]
