## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Importing Dataset

In [3]:
dataset = pd.read_csv('./data/csv_experiments.csv')

In [4]:
dataset

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web01_00000  2019-04-24 09:32:38.933896   
1              1  zoo_web01_00001  2019-04-24 09:34:03.537255   
2              2  zoo_web01_00002  2019-04-24 09:35:29.014469   
3              3  zoo_web01_00003  2019-04-24 09:36:54.624078   
4              4  zoo_web01_00004  2019-04-24 09:38:20.834317   
...          ...              ...                         ...   
1595        1595  zoo_web01_01595  2019-04-25 23:37:19.919669   
1596        1596  zoo_web01_01596  2019-04-25 23:38:45.630355   
1597        1597  zoo_web01_01597  2019-04-25 23:40:12.605801   
1598        1598  zoo_web01_01598  2019-04-25 23:41:38.332062   
1599        1599  zoo_web01_01599  2019-04-25 23:43:04.385405   

                 experiment_stop  \
0     2019-04-24 09:33:38.995087   
1     2019-04-24 09:35:03.597516   
2     2019-04-24 09:36:29.075269   
3     2019-04-24 09:37:54.685378   
4     2019-04-24 09:39:20.895537   
...                          ...   
1595  2019-04-25 23:38:19.981931   
1596  2019-04-25 23:39:45.689179   
1597  2019-04-25 23:41:12.666519   
1598  2019-04-25 23:42:38.401912   
1599  2019-04-25 23:44:04.502453   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                                 NaN   
1                                            107128.0   
2                                                 NaN   
3                                            107065.0   
4                                            105343.0   
...                                               ...   
1595                                            299.0   
1596                                            302.0   
1597                                            300.0   
1598                                            307.0   
1599                                            304.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             NaN   
1                                             1.0   
2                                             NaN   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         NaN   
1                                         0.0   
2                                         NaN   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                      NaN   
1                                        /   
2                                      NaN   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              NaN   
1                                              0.0   
2                                              NaN   
3                                              0.0   
4                                              0.0   
... 

## Removing columns whose entire column is zero

In [5]:
def all_entries_nonzero(column):
    return (column != 0).any()

columns_to_drop = dataset.columns[~dataset.apply(all_entries_nonzero)]
dataset_new = dataset.drop(columns_to_drop, axis=1)


In [6]:
dataset_new

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web01_00000  2019-04-24 09:32:38.933896   
1              1  zoo_web01_00001  2019-04-24 09:34:03.537255   
2              2  zoo_web01_00002  2019-04-24 09:35:29.014469   
3              3  zoo_web01_00003  2019-04-24 09:36:54.624078   
4              4  zoo_web01_00004  2019-04-24 09:38:20.834317   
...          ...              ...                         ...   
1595        1595  zoo_web01_01595  2019-04-25 23:37:19.919669   
1596        1596  zoo_web01_01596  2019-04-25 23:38:45.630355   
1597        1597  zoo_web01_01597  2019-04-25 23:40:12.605801   
1598        1598  zoo_web01_01598  2019-04-25 23:41:38.332062   
1599        1599  zoo_web01_01599  2019-04-25 23:43:04.385405   

                 experiment_stop  \
0     2019-04-24 09:33:38.995087   
1     2019-04-24 09:35:03.597516   
2     2019-04-24 09:36:29.075269   
3     2019-04-24 09:37:54.685378   
4     2019-04-24 09:39:20.895537   
...                          ...   
1595  2019-04-25 23:38:19.981931   
1596  2019-04-25 23:39:45.689179   
1597  2019-04-25 23:41:12.666519   
1598  2019-04-25 23:42:38.401912   
1599  2019-04-25 23:44:04.502453   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                                 NaN   
1                                            107128.0   
2                                                 NaN   
3                                            107065.0   
4                                            105343.0   
...                                               ...   
1595                                            299.0   
1596                                            302.0   
1597                                            300.0   
1598                                            307.0   
1599                                            304.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             NaN   
1                                             1.0   
2                                             NaN   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         NaN   
1                                         0.0   
2                                         NaN   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                      NaN   
1                                        /   
2                                      NaN   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              NaN   
1                                              0.0   
2                                              NaN   
3                                              0.0   
4                                              0.0   
... 

# Checking for any Null values in dataset


In [7]:
dataset_new = dataset_new.replace('', np.nan)
dataset_new.isnull().sum()

Unnamed: 0                                           0
experiment_name                                      0
experiment_start                                     0
experiment_stop                                      0
metric__mp.input.vdu01.0__ab_completed_requests    221
                                                  ... 
param__mp__mp.output__address                        0
param__mp__mp.output__connection_point               0
param__mp__mp.output__container                      0
param__mp__mp.output__name                           0
run_id                                               0
Length: 77, dtype: int64

In [8]:
dataset_new = dataset_new.dropna(axis=1, how='all')
dataset_new.isnull().sum()

Unnamed: 0                                           0
experiment_name                                      0
experiment_start                                     0
experiment_stop                                      0
metric__mp.input.vdu01.0__ab_completed_requests    221
                                                  ... 
param__mp__mp.output__address                        0
param__mp__mp.output__connection_point               0
param__mp__mp.output__container                      0
param__mp__mp.output__name                           0
run_id                                               0
Length: 67, dtype: int64

In [9]:
dataset_new

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web01_00000  2019-04-24 09:32:38.933896   
1              1  zoo_web01_00001  2019-04-24 09:34:03.537255   
2              2  zoo_web01_00002  2019-04-24 09:35:29.014469   
3              3  zoo_web01_00003  2019-04-24 09:36:54.624078   
4              4  zoo_web01_00004  2019-04-24 09:38:20.834317   
...          ...              ...                         ...   
1595        1595  zoo_web01_01595  2019-04-25 23:37:19.919669   
1596        1596  zoo_web01_01596  2019-04-25 23:38:45.630355   
1597        1597  zoo_web01_01597  2019-04-25 23:40:12.605801   
1598        1598  zoo_web01_01598  2019-04-25 23:41:38.332062   
1599        1599  zoo_web01_01599  2019-04-25 23:43:04.385405   

                 experiment_stop  \
0     2019-04-24 09:33:38.995087   
1     2019-04-24 09:35:03.597516   
2     2019-04-24 09:36:29.075269   
3     2019-04-24 09:37:54.685378   
4     2019-04-24 09:39:20.895537   
...                          ...   
1595  2019-04-25 23:38:19.981931   
1596  2019-04-25 23:39:45.689179   
1597  2019-04-25 23:41:12.666519   
1598  2019-04-25 23:42:38.401912   
1599  2019-04-25 23:44:04.502453   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                                 NaN   
1                                            107128.0   
2                                                 NaN   
3                                            107065.0   
4                                            105343.0   
...                                               ...   
1595                                            299.0   
1596                                            302.0   
1597                                            300.0   
1598                                            307.0   
1599                                            304.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             NaN   
1                                             1.0   
2                                             NaN   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         NaN   
1                                         0.0   
2                                         NaN   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                      NaN   
1                                        /   
2                                      NaN   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              NaN   
1                                              0.0   
2                                              NaN   
3                                              0.0   
4                                              0.0   
... 

In [10]:
def all_values_same(column):
    return column.nunique() == 1

columns_to_drop = dataset_new.columns[dataset_new.apply(all_values_same)]
dataset_new = dataset_new.drop(columns_to_drop, axis=1)

In [11]:
dataset_new.isnull().sum()

Unnamed: 0                                                       0
experiment_name                                                  0
experiment_start                                                 0
experiment_stop                                                  0
metric__mp.input.vdu01.0__ab_completed_requests                221
metric__mp.input.vdu01.0__ab_doc_length                        221
metric__mp.input.vdu01.0__ab_doc_path                          221
metric__mp.input.vdu01.0__ab_html_transfer_byte                221
metric__mp.input.vdu01.0__ab_mean_time_per_request             221
metric__mp.input.vdu01.0__ab_request_per_second                221
metric__mp.input.vdu01.0__ab_rt_percentiles_csv                220
metric__mp.input.vdu01.0__ab_time_used_s                       221
metric__mp.input.vdu01.0__ab_total_transfer_byte               221
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    221
metric__mp.input.vdu01.0__stat__data__rx_bytes                

In [12]:
dataset_new = dataset_new.dropna()

In [13]:
dataset_new.isnull().sum()

Unnamed: 0                                                     0
experiment_name                                                0
experiment_start                                               0
experiment_stop                                                0
metric__mp.input.vdu01.0__ab_completed_requests                0
metric__mp.input.vdu01.0__ab_doc_length                        0
metric__mp.input.vdu01.0__ab_doc_path                          0
metric__mp.input.vdu01.0__ab_html_transfer_byte                0
metric__mp.input.vdu01.0__ab_mean_time_per_request             0
metric__mp.input.vdu01.0__ab_request_per_second                0
metric__mp.input.vdu01.0__ab_rt_percentiles_csv                0
metric__mp.input.vdu01.0__ab_time_used_s                       0
metric__mp.input.vdu01.0__ab_total_transfer_byte               0
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    0
metric__mp.input.vdu01.0__stat__data__rx_bytes                 0
metric__mp.input.vdu01.0_

In [14]:
dataset_new.columns

Index(['Unnamed: 0', 'experiment_name', 'experiment_start', 'experiment_stop',
       'metric__mp.input.vdu01.0__ab_completed_requests',
       'metric__mp.input.vdu01.0__ab_doc_length',
       'metric__mp.input.vdu01.0__ab_doc_path',
       'metric__mp.input.vdu01.0__ab_html_transfer_byte',
       'metric__mp.input.vdu01.0__ab_mean_time_per_request',
       'metric__mp.input.vdu01.0__ab_request_per_second',
       'metric__mp.input.vdu01.0__ab_rt_percentiles_csv',
       'metric__mp.input.vdu01.0__ab_time_used_s',
       'metric__mp.input.vdu01.0__ab_total_transfer_byte',
       'metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
  

In [15]:
dataset_new = dataset_new.drop(['Unnamed: 0','experiment_name', 'experiment_start', 'experiment_stop', 'metric__mp.input.vdu01.0__ab_doc_path', 'metric__mp.input.vdu01.0__ab_rt_percentiles_csv', 'param__func__mp.input__cmd_start', 'param__header__all__config_id', 'param__header__all__repetition', 'run_id'],axis=1)
dataset_new.columns

Index(['metric__mp.input.vdu01.0__ab_completed_requests',
       'metric__mp.input.vdu01.0__ab_doc_length',
       'metric__mp.input.vdu01.0__ab_html_transfer_byte',
       'metric__mp.input.vdu01.0__ab_mean_time_per_request',
       'metric__mp.input.vdu01.0__ab_request_per_second',
       'metric__mp.input.vdu01.0__ab_time_used_s',
       'metric__mp.input.vdu01.0__ab_total_transfer_byte',
       'metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__rx_bytes',
       'metric__mp.output.vdu01.0__stat__data__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__tx_bytes',
       'met

In [16]:
dataset_new.dtypes

metric__mp.input.vdu01.0__ab_completed_requests                float64
metric__mp.input.vdu01.0__ab_doc_length                        float64
metric__mp.input.vdu01.0__ab_html_transfer_byte                float64
metric__mp.input.vdu01.0__ab_mean_time_per_request             float64
metric__mp.input.vdu01.0__ab_request_per_second                float64
metric__mp.input.vdu01.0__ab_time_used_s                       float64
metric__mp.input.vdu01.0__ab_total_transfer_byte               float64
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    float64
metric__mp.input.vdu01.0__stat__data__rx_bytes                 float64
metric__mp.input.vdu01.0__stat__data__rx_packets               float64
metric__mp.input.vdu01.0__stat__data__tx_bytes                 float64
metric__mp.input.vdu01.0__stat__data__tx_packets               float64
metric__mp.input.vdu01.0__stat__eth0__rx_bytes                 float64
metric__mp.input.vdu01.0__stat__eth0__rx_packets               float64
metric

In [17]:
X = dataset_new.iloc[:, :-2].values
y = dataset_new.iloc[:, -2:].values

In [18]:
print(y)

[[1.00e-01 6.40e+01]
 [1.00e-01 6.40e+01]
 [1.00e-01 6.40e+01]
 ...
 [1.00e+00 5.12e+02]
 [1.00e+00 5.12e+02]
 [1.00e+00 5.12e+02]]


## One Hot Encoding mem_max variable

In [19]:
data = dataset_new['param__func__de.upb.lb-nginx.0.1__mem_max']
encoded_data = pd.get_dummies(data, columns=['param__func__de.upb.lb-nginx.0.1__mem_max'])
dataset_new = dataset_new.drop('param__func__de.upb.lb-nginx.0.1__mem_max', axis = 1)
dataset_new = pd.concat([dataset_new, encoded_data], axis=1)
dataset_new

metric__mp.input.vdu01.0__ab_completed_requests  \
1                                            107128.0   
3                                            107065.0   
4                                            105343.0   
5                                            107447.0   
6                                            106411.0   
...                                               ...   
1595                                            299.0   
1596                                            302.0   
1597                                            300.0   
1598                                            307.0   
1599                                            304.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
1                                         0.0   
3                                         0.0   
4                                         0.0   
5                                         0.0   
6                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

      metric__mp.input.vdu01.0__ab_html_transfer_byte  \
1                                        0.000000e+00   
3                                        0.000000e+00   
4                                        0.000000e+00   
5                                        0.000000e+00   
6                                        0.000000e+00   
...                                               ...   
1595                                     9.519819e+10   
1596                                     9.615335e+10   
1597                                     9.551658e+10   
1598                                     9.774530e+10   
1599                                     9.679013e+10   

      metric__mp.input.vdu01.0__ab_mean_time_per_request  \
1                                                 0.561    
3                                                 0.560    
4                                                 0.570    
5                                                 0.560    
6                                                 0.564    
...                                                 ...    
1595                                            201.221    
1596                                            199.165    
1597                                            200.120    
1598                                            195.913    
1599                                            197.455    

      metric__mp.input.vdu01.0__ab_request_per_second  \
1                                             1783.06   
3                                             1784.42   
4                                             1755.71   
5                                             1784.80   
6                                             1773.52   
...                                               ...   
1595                                             4.97   
1596                                             5.02   
1597                                             5.00   
1598                                             5.10   
1599                                             5.06   

      metric__mp.input.vdu01.0__ab_time_used_s  \
1                                       60.081   
3                                       60.000   
4                                       60.000   
5                                       60.201   
6                                       60.000   
...                                        ...   
1595                                    60.165   
1596                                    60.148   
1597                                    60.036   
1598                                    60.145   
1599                                    60.026   

      metric__mp.input.vdu01.0__ab_total

In [20]:
y= dataset_new.iloc[:, -5:].values
print(y)

[[0.1 1.  0.  0.  0. ]
 [0.1 1.  0.  0.  0. ]
 [0.1 1.  0.  0.  0. ]
 ...
 [1.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  1. ]]


## Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Separate the two output features
y_train_output1 = y_train[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_train_output2 = y_train[:, -4]  # Second column for binary classification

y_train_output3 = y_train[:, -3]
y_train_output4 = y_train[:, -2]
y_train_output5 = y_train[:, -1]

y_test_output1 = y_test[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_test_output2 = y_test[:, -4]  # Second column for binary classification

y_test_output3 = y_test[:, -3]
y_test_output4 = y_test[:, -2]
y_test_output5 = y_test[:, -1]

In [22]:
print(y_train_output1)

[0.3 0.7 0.6 ... 0.9 0.5 0.6]


## Feature Scaling

In [23]:
from sklearn.preprocessing import MinMaxScaler

# Normalize input features
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)



In [24]:
print(X_train_normalized)

[[1.31184681e-04 1.00000000e+00 2.79220779e-01 ... 2.38512992e-01
  8.56997440e-02 2.06336874e-01]
 [9.63012167e-01 0.00000000e+00 0.00000000e+00 ... 2.30109060e-01
  9.61880063e-01 8.98642387e-01]
 [9.65798280e-01 0.00000000e+00 0.00000000e+00 ... 2.30966542e-01
  9.64746033e-01 9.01442590e-01]
 ...
 [5.20574131e-04 1.00000000e+00 8.86363636e-01 ... 8.76039079e-01
  3.51152647e-01 8.56752656e-01]
 [2.58204769e-04 1.00000000e+00 4.77272727e-01 ... 4.44633556e-01
  1.62697458e-01 3.96066768e-01]
 [9.60975681e-01 0.00000000e+00 0.00000000e+00 ... 2.29482297e-01
  9.59776838e-01 8.96574608e-01]]


In [25]:
print(type(y_train_output1))
print(type(y_train_output2))
print(type(y_train_output3))
print(type(y_train_output4))
print(type(y_train_output5))

print(type(y_test_output1))
print(type(y_test_output2))
print(type(y_test_output3))
print(type(y_test_output4))
print(type(y_test_output5))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [26]:
print(X_train_normalized.shape)
print(y_train_output1.shape)
print(y_train_output2.shape)
print(y_train_output3.shape)
print(y_train_output4.shape)
print(y_train_output5.shape)

print(y_test_output1.shape)
print(y_test_output2.shape)
print(y_test_output3.shape)
print(y_test_output4.shape)
print(y_test_output5.shape)

(1103, 32)
(1103,)
(1103,)
(1103,)
(1103,)
(1103,)
(276,)
(276,)
(276,)
(276,)
(276,)


## Building Model

In [27]:
input_shape = (32,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=64, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dense(units=32, activation='relu')(x)
output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification

output_3 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_3')(x)  # Output 2: Classification
output_4 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_4')(x)  # Output 2: Classification
output_5 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_5')(x)  # Output 2: Classification

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2, output_3, output_4, output_5])

# Check the model output names
print("Model Output Names:", model.output_names)  


Model Output Names: ['output_1', 'output_2', 'output_3', 'output_4', 'output_5']


In [28]:
model.compile(
    loss={
        'output_1': 'mean_squared_error',  # Regression loss function
        'output_2': 'binary_crossentropy',  # Categorical classification loss function
        'output_3': 'binary_crossentropy',
        'output_4': 'binary_crossentropy',
        'output_5': 'binary_crossentropy',
    },
    optimizer='adam',
    metrics={
        'output_1': ['mae', 'mse'],
        'output_2': 'accuracy',
        'output_3': 'accuracy',
        'output_4': 'accuracy',
        'output_5': 'accuracy',
    }
)

model.fit(X_train_normalized, {'output_1': y_train_output1, 'output_2': y_train_output2, 'output_3': y_train_output3, 'output_4': y_train_output4, 'output_5': y_train_output5},
          validation_data=(X_test_normalized, {'output_1': y_test_output1, 'output_2': y_test_output2, 'output_3': y_test_output3, 'output_4': y_test_output4, 'output_5': y_test_output5}),
          epochs=50, batch_size=32)



Epoch 1/50
35/35 [==============================] - 4s 41ms/step - loss: 2.6059 - output_1_loss: 0.1800 - output_2_loss: 0.6068 - output_3_loss: 0.6222 - output_4_loss: 0.5807 - output_5_loss: 0.6161 - output_1_mae: 0.3149 - output_1_mse: 0.1800 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7180 - output_4_accuracy: 0.7643 - output_5_accuracy: 0.7543 - val_loss: 2.3027 - val_output_1_loss: 0.0383 - val_output_2_loss: 0.5263 - val_output_3_loss: 0.5598 - val_output_4_loss: 0.5882 - val_output_5_loss: 0.5902 - val_output_1_mae: 0.1688 - val_output_1_mse: 0.0383 - val_output_2_accuracy: 0.7826 - val_output_3_accuracy: 0.7609 - val_output_4_accuracy: 0.7283 - val_output_5_accuracy: 0.7283
Epoch 2/50
35/35 [==============================] - 0s 9ms/step - loss: 2.3085 - output_1_loss: 0.0333 - output_2_loss: 0.5887 - output_3_loss: 0.5704 - output_4_loss: 0.5511 - output_5_loss: 0.5650 - output_1_mae: 0.1460 - output_1_mse: 0.0333 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498 

Epoch 13/50
35/35 [==============================] - 0s 8ms/step - loss: 2.2620 - output_1_loss: 0.0187 - output_2_loss: 0.5784 - output_3_loss: 0.5604 - output_4_loss: 0.5505 - output_5_loss: 0.5540 - output_1_mae: 0.1004 - output_1_mse: 0.0187 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498 - output_4_accuracy: 0.7643 - output_5_accuracy: 0.7543 - val_loss: 2.2805 - val_output_1_loss: 0.0195 - val_output_2_loss: 0.5308 - val_output_3_loss: 0.5499 - val_output_4_loss: 0.5895 - val_output_5_loss: 0.5908 - val_output_1_mae: 0.1072 - val_output_1_mse: 0.0195 - val_output_2_accuracy: 0.7826 - val_output_3_accuracy: 0.7609 - val_output_4_accuracy: 0.7283 - val_output_5_accuracy: 0.7283
Epoch 14/50
35/35 [==============================] - 0s 9ms/step - loss: 2.2677 - output_1_loss: 0.0195 - output_2_loss: 0.5829 - output_3_loss: 0.5637 - output_4_loss: 0.5481 - output_5_loss: 0.5536 - output_1_mae: 0.1010 - output_1_mse: 0.0195 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498

Epoch 25/50
35/35 [==============================] - 0s 9ms/step - loss: 2.2510 - output_1_loss: 0.0171 - output_2_loss: 0.5779 - output_3_loss: 0.5577 - output_4_loss: 0.5452 - output_5_loss: 0.5531 - output_1_mae: 0.0943 - output_1_mse: 0.0171 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498 - output_4_accuracy: 0.7643 - output_5_accuracy: 0.7543 - val_loss: 2.2928 - val_output_1_loss: 0.0185 - val_output_2_loss: 0.5386 - val_output_3_loss: 0.5504 - val_output_4_loss: 0.5936 - val_output_5_loss: 0.5918 - val_output_1_mae: 0.1039 - val_output_1_mse: 0.0185 - val_output_2_accuracy: 0.7826 - val_output_3_accuracy: 0.7609 - val_output_4_accuracy: 0.7283 - val_output_5_accuracy: 0.7283
Epoch 26/50
35/35 [==============================] - 0s 8ms/step - loss: 2.2461 - output_1_loss: 0.0161 - output_2_loss: 0.5785 - output_3_loss: 0.5545 - output_4_loss: 0.5459 - output_5_loss: 0.5510 - output_1_mae: 0.0933 - output_1_mse: 0.0161 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498

Epoch 37/50
35/35 [==============================] - 0s 9ms/step - loss: 2.2452 - output_1_loss: 0.0175 - output_2_loss: 0.5780 - output_3_loss: 0.5557 - output_4_loss: 0.5468 - output_5_loss: 0.5471 - output_1_mae: 0.0967 - output_1_mse: 0.0175 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498 - output_4_accuracy: 0.7643 - output_5_accuracy: 0.7534 - val_loss: 2.2919 - val_output_1_loss: 0.0194 - val_output_2_loss: 0.5354 - val_output_3_loss: 0.5505 - val_output_4_loss: 0.5934 - val_output_5_loss: 0.5932 - val_output_1_mae: 0.1007 - val_output_1_mse: 0.0194 - val_output_2_accuracy: 0.7826 - val_output_3_accuracy: 0.7609 - val_output_4_accuracy: 0.7283 - val_output_5_accuracy: 0.7283
Epoch 38/50
35/35 [==============================] - 0s 8ms/step - loss: 2.2449 - output_1_loss: 0.0171 - output_2_loss: 0.5756 - output_3_loss: 0.5540 - output_4_loss: 0.5458 - output_5_loss: 0.5523 - output_1_mae: 0.0942 - output_1_mse: 0.0171 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498

Epoch 49/50
35/35 [==============================] - 0s 9ms/step - loss: 2.2319 - output_1_loss: 0.0177 - output_2_loss: 0.5714 - output_3_loss: 0.5536 - output_4_loss: 0.5437 - output_5_loss: 0.5455 - output_1_mae: 0.0964 - output_1_mse: 0.0177 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498 - output_4_accuracy: 0.7643 - output_5_accuracy: 0.7525 - val_loss: 2.2850 - val_output_1_loss: 0.0157 - val_output_2_loss: 0.5299 - val_output_3_loss: 0.5521 - val_output_4_loss: 0.5954 - val_output_5_loss: 0.5920 - val_output_1_mae: 0.0940 - val_output_1_mse: 0.0157 - val_output_2_accuracy: 0.7826 - val_output_3_accuracy: 0.7609 - val_output_4_accuracy: 0.7283 - val_output_5_accuracy: 0.7319
Epoch 50/50
35/35 [==============================] - 0s 9ms/step - loss: 2.2348 - output_1_loss: 0.0172 - output_2_loss: 0.5767 - output_3_loss: 0.5520 - output_4_loss: 0.5448 - output_5_loss: 0.5441 - output_1_mae: 0.0944 - output_1_mse: 0.0172 - output_2_accuracy: 0.7316 - output_3_accuracy: 0.7498

In [29]:
# After the model is trained, you can make predictions
y_pred_output1, y_pred_output2, y_pred_output3, y_pred_output4, y_pred_output5 = model.predict(X_test_normalized)

# For output_1 (Regression)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_output1 = mean_absolute_error(y_test_output1, y_pred_output1)
mse_output1 = mean_squared_error(y_test_output1, y_pred_output1)
r2_output1 = r2_score(y_test_output1, y_pred_output1)

print("Output 1 - Mean Absolute Error:", mae_output1)
print("Output 1 - Mean Squared Error:", mse_output1)
print("Output 1 - R^2 Score:", r2_output1)

# For output_2 to output_5 (Classification)
from sklearn.metrics import accuracy_score, confusion_matrix

for i in range(4):
    cm = confusion_matrix(y_test_output2, np.round(y_pred_output2))
    accuracy = accuracy_score(y_test_output2, np.round(y_pred_output2))
    print(f"Confusion Matrix for Classification Output {i+2}:\n{cm}")
    print(f"Accuracy Score for Classification Output {i+2}: {accuracy}")




9/9 [==============================] - 0s 3ms/step
Output 1 - Mean Absolute Error: 0.09686918686940402
Output 1 - Mean Squared Error: 0.015932615552935594
Output 1 - R^2 Score: 0.7918507446863616
Confusion Matrix for Classification Output 2:
[[216   0]
 [ 60   0]]
Accuracy Score for Classification Output 2: 0.782608695652174
Confusion Matrix for Classification Output 3:
[[216   0]
 [ 60   0]]
Accuracy Score for Classification Output 3: 0.782608695652174
Confusion Matrix for Classification Output 4:
[[216   0]
 [ 60   0]]
Accuracy Score for Classification Output 4: 0.782608695652174
Confusion Matrix for Classification Output 5:
[[216   0]
 [ 60   0]]
Accuracy Score for Classification Output 5: 0.782608695652174


In [30]:
y_test1 = y_test[:,0]

rounded_y_pred = y_pred_output1.reshape(len(y_pred_output1), 1).round(1)

# Reshape y_test1 to a column vector
y_test1_reshaped = y_test1.reshape(len(y_test1), 1)

# Concatenate both arrays side by side (along axis 1)
result = np.concatenate((rounded_y_pred, y_test1_reshaped), axis=1)
np.set_printoptions(precision=1)
print(result)

[[0.7 0.6]
 [0.7 0.8]
 [0.4 0.4]
 [0.6 0.7]
 [0.6 0.7]
 [0.2 0.2]
 [0.3 0.3]
 [0.3 0.3]
 [0.6 0.5]
 [0.4 0.4]
 [0.4 0.5]
 [0.9 1. ]
 [0.7 0.8]
 [0.6 0.4]
 [0.  0.1]
 [0.6 0.9]
 [0.7 0.7]
 [0.8 0.9]
 [0.8 0.9]
 [0.8 0.9]
 [0.6 0.5]
 [0.4 0.5]
 [0.6 0.8]
 [0.3 0.3]
 [0.8 0.9]
 [0.6 0.6]
 [0.3 0.3]
 [0.4 0.5]
 [0.7 0.8]
 [0.6 0.9]
 [0.7 0.7]
 [0.3 0.3]
 [0.8 1. ]
 [0.6 0.5]
 [0.1 0.1]
 [0.7 0.8]
 [0.6 0.6]
 [0.6 0.9]
 [0.1 0.2]
 [0.6 0.5]
 [0.1 0.2]
 [0.3 0.3]
 [0.9 1. ]
 [0.3 0.3]
 [0.5 0.5]
 [0.6 0.7]
 [0.4 0.5]
 [0.4 0.5]
 [0.6 0.4]
 [0.7 0.8]
 [0.8 0.8]
 [0.6 0.6]
 [0.  0.1]
 [0.7 0.8]
 [0.6 0.9]
 [0.1 0.1]
 [0.8 0.8]
 [0.4 0.5]
 [0.7 0.8]
 [0.4 0.3]
 [0.3 0.3]
 [0.8 0.7]
 [0.9 1. ]
 [0.8 0.9]
 [0.6 0.4]
 [0.2 0.2]
 [0.2 0.2]
 [0.6 0.7]
 [0.6 0.3]
 [0.6 0.7]
 [0.6 0.6]
 [0.6 0.9]
 [0.8 0.8]
 [0.1 0.1]
 [0.5 0.6]
 [0.8 1. ]
 [0.1 0.1]
 [0.1 0.2]
 [0.1 0.1]
 [0.6 0.5]
 [0.6 0.5]
 [0.6 0.4]
 [0.8 1. ]
 [0.6 0.8]
 [0.1 0.1]
 [0.6 0.6]
 [0.6 0.7]
 [0.9 1. ]
 [0.2 0.2]
 [0.6 0.7]
 [0.3 0.3]

## K-fold Cross Validation

In [31]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

num_folds = 5

# Initialize lists to store the evaluation metrics for each fold
mse_output1_list = []
accuracy_output2_list = []
accuracy_output3_list = []
accuracy_output4_list = []
accuracy_output5_list = []

# Create the KFold object
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)


# Create the model
input_shape = (32,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=256, activation='relu')(inputs)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation
   

output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification
output_3 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_3')(x)
output_4 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_4')(x)
output_5 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_5')(x)

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2, output_3, output_4, output_5])

# Perform 5-fold cross-validation
for fold, (train_indices, val_indices) in enumerate(kfold.split(X_train_normalized)):
    print(f"Fold {fold+1}/{num_folds}")
    
    # Split the data into training and validation sets for this fold
    X_train_fold = X_train_normalized[train_indices]
    X_val_fold = X_train_normalized[val_indices]
    y_train_output1_fold = y_train_output1[train_indices]
    y_train_output2_fold = y_train_output2[train_indices]
    y_train_output3_fold = y_train_output3[train_indices]
    y_train_output4_fold = y_train_output4[train_indices]
    y_train_output5_fold = y_train_output5[train_indices]
    
    y_val_output1_fold = y_train_output1[val_indices]
    y_val_output2_fold = y_train_output2[val_indices]
    y_val_output3_fold = y_train_output3[val_indices]
    y_val_output4_fold = y_train_output4[val_indices]
    y_val_output5_fold = y_train_output5[val_indices]
    
    
    # Compile the model
    model.compile(
        loss={
            'output_1': 'mean_squared_error',  # Regression loss function
            'output_2': 'binary_crossentropy',  # classification loss function
            'output_3': 'binary_crossentropy',
            'output_4': 'binary_crossentropy',
            'output_5': 'binary_crossentropy',
        },
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        metrics={
            'output_1': ['mae', 'mse'],
            'output_2': 'accuracy',
            'output_3': 'accuracy',
            'output_4': 'accuracy',
            'output_5': 'accuracy',
        }
    )
    

    # Train the model
    model.fit(X_train_fold, {'output_1': y_train_output1_fold, 'output_2': y_train_output2_fold, 'output_3': y_train_output3_fold, 'output_4': y_train_output4_fold, 'output_5': y_train_output5_fold},
          epochs=100, batch_size=32, verbose=0)

    
    # Evaluate the model on validation data for this fold
    results = model.evaluate(X_val_fold, {'output_1': y_val_output1_fold, 'output_2': y_val_output2_fold, 'output_3': y_val_output3_fold, 'output_4': y_val_output4_fold, 'output_5': y_val_output5_fold})
#     print("Results:", results)
    
    mse_output1_list.append(results[2])  # Index 2 corresponds to MSE for 'output_1'
    accuracy_output2_list.append(results[8])  # Index 5 corresponds to accuracy for 'output_2'
    accuracy_output3_list.append(results[9])  # Index 8 corresponds to accuracy for 'output_3'
    accuracy_output4_list.append(results[10])  # Index 11 corresponds to accuracy for 'output_4'
    accuracy_output5_list.append(results[11])  # Index 14 corresponds to accuracy for 'output_5'




Fold 1/5
7/7 [==============================] - 1s 8ms/step - loss: 3.2149 - output_1_loss: 0.0173 - output_2_loss: 0.8252 - output_3_loss: 0.9044 - output_4_loss: 0.7432 - output_5_loss: 0.7248 - output_1_mae: 0.0928 - output_1_mse: 0.0173 - output_2_accuracy: 0.6606 - output_3_accuracy: 0.7014 - output_4_accuracy: 0.7240 - output_5_accuracy: 0.7511
Fold 2/5
7/7 [==============================] - 1s 7ms/step - loss: 3.6987 - output_1_loss: 0.0224 - output_2_loss: 1.0548 - output_3_loss: 0.9515 - output_4_loss: 0.8042 - output_5_loss: 0.8658 - output_1_mae: 0.1135 - output_1_mse: 0.0224 - output_2_accuracy: 0.6380 - output_3_accuracy: 0.6787 - output_4_accuracy: 0.7195 - output_5_accuracy: 0.6968
Fold 3/5
7/7 [==============================] - 1s 8ms/step - loss: 3.1837 - output_1_loss: 0.0186 - output_2_loss: 0.7594 - output_3_loss: 0.8786 - output_4_loss: 0.7944 - output_5_loss: 0.7327 - output_1_mae: 0.1015 - output_1_mse: 0.0186 - output_2_accuracy: 0.7466 - output_3_accuracy: 0.70

In [32]:
# Calculate the mean and standard deviation of evaluation metrics across all folds
mean_mse_output1 = np.mean(mse_output1_list)
mean_accuracy_output2 = np.mean(accuracy_output2_list)
mean_accuracy_output3 = np.mean(accuracy_output3_list)
mean_accuracy_output4 = np.mean(accuracy_output4_list)
mean_accuracy_output5 = np.mean(accuracy_output5_list)


std_mse_output1 = np.std(mse_output1_list)
std_accuracy_output2 = np.std(accuracy_output2_list)
std_accuracy_output3 = np.std(accuracy_output3_list)
std_accuracy_output4 = np.std(accuracy_output4_list)
std_accuracy_output5 = np.std(accuracy_output5_list)

# For regression task (output_1) - Calculate R-squared (R^2) score
y_true_output1 = np.concatenate([y_train_output1, y_test_output1])
y_pred_output1 = model.predict(np.concatenate([X_train_normalized, X_test_normalized]))[0]
r2_output1 = r2_score(y_true_output1, y_pred_output1)

print("Mean MSE (Output 1):", mean_mse_output1)
print("Mean Accuracy (Output 2):", mean_accuracy_output2)
print("Mean Accuracy (Output 3):", mean_accuracy_output3)
print("Mean Accuracy (Output 4):", mean_accuracy_output4)
print("Mean Accuracy (Output 5):", mean_accuracy_output5)

print("Standard Deviation MSE (Output 1):", std_mse_output1)
print("Standard Deviation Accuracy (Output 2):", std_accuracy_output2)
print("Standard Deviation Accuracy (Output 3):", std_accuracy_output3)
print("Standard Deviation Accuracy (Output 4):", std_accuracy_output4)
print("Standard Deviation Accuracy (Output 5):", std_accuracy_output5)

print("R^2 Score (Output 1 - Regression):", r2_output1)


44/44 [==============================] - 1s 4ms/step
Mean MSE (Output 1): 0.8460030436515809
Mean Accuracy (Output 2): 0.6981406927108764
Mean Accuracy (Output 3): 0.7135582089424133
Mean Accuracy (Output 4): 0.7143809199333191
Mean Accuracy (Output 5): 0.7252982497215271
Standard Deviation MSE (Output 1): 0.1260145061444494
Standard Deviation Accuracy (Output 2): 0.04605499706773064
Standard Deviation Accuracy (Output 3): 0.02967932183524274
Standard Deviation Accuracy (Output 4): 0.017531468416657245
Standard Deviation Accuracy (Output 5): 0.01724625527712655
R^2 Score (Output 1 - Regression): 0.803751597169972


In [33]:
# 1. Compare Regression Output with Original Test Values

# Predict using the trained model on the test data for the regression output (output_1)
y_pred_output1_test = model.predict(X_test_normalized)[0]

# Reshape the predictions and original test values to match for comparison
y_pred_output1_test = y_pred_output1_test.flatten()

# Convert both arrays to the same data type (e.g., float64) for comparison
y_test_output1 = y_test_output1.astype(np.float64)
y_pred_output1_test = y_pred_output1_test.astype(np.float64)

# Stack the original test values and predicted values horizontally
comparison_output1 = np.column_stack((y_test_output1, y_pred_output1_test))

# Print the original test values and predicted values side by side
print("Original Test Values (Output 1) vs. Predicted Values (Output 1):")
print(comparison_output1)

9/9 [==============================] - 0s 4ms/step
Original Test Values (Output 1) vs. Predicted Values (Output 1):
[[ 0.6  0.5]
 [ 0.8  0.8]
 [ 0.4  0.5]
 [ 0.7  0.7]
 [ 0.7  0.5]
 [ 0.2  0.2]
 [ 0.3  0.3]
 [ 0.3  0.2]
 [ 0.5  0.7]
 [ 0.4  0.5]
 [ 0.5  0.4]
 [ 1.   1. ]
 [ 0.8  0.8]
 [ 0.4  0.6]
 [ 0.1  0. ]
 [ 0.9  0.6]
 [ 0.7  0.8]
 [ 0.9  0.9]
 [ 0.9  0.9]
 [ 0.9  1. ]
 [ 0.5  0.6]
 [ 0.5  0.4]
 [ 0.8  0.7]
 [ 0.3  0.3]
 [ 0.9  0.8]
 [ 0.6  0.7]
 [ 0.3  0.3]
 [ 0.5  0.5]
 [ 0.8  0.7]
 [ 0.9  0.6]
 [ 0.7  0.7]
 [ 0.3  0.3]
 [ 1.   1. ]
 [ 0.5  0.7]
 [ 0.1  0.1]
 [ 0.8  0.7]
 [ 0.6  0.6]
 [ 0.9  0.7]
 [ 0.2  0.2]
 [ 0.5  0.5]
 [ 0.2  0.3]
 [ 0.3  0.2]
 [ 1.   1. ]
 [ 0.3  0.3]
 [ 0.5  0.5]
 [ 0.7  0.7]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.4  0.6]
 [ 0.8  0.7]
 [ 0.8  0.9]
 [ 0.6  0.6]
 [ 0.1  0.1]
 [ 0.8  0.7]
 [ 0.9  0.7]
 [ 0.1  0.1]
 [ 0.8  0.6]
 [ 0.5  0.5]
 [ 0.8  0.7]
 [ 0.3  0.3]
 [ 0.3  0.3]
 [ 0.7  0.9]
 [ 1.   1. ]
 [ 0.9  0.8]
 [ 0.4  0.6]
 [ 0.2  0.2]
 [ 0.2  0.2]
 [ 0.7  0.6]


In [34]:
# 2. Generate Confusion Matrix for Classification

# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output2_test = model.predict(X_test_normalized)[1]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output2_test_binary = np.round(y_pred_output2_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output2 = confusion_matrix(y_test_output2, y_pred_output2_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 2 - Classification):")
print(conf_matrix_output2)

9/9 [==============================] - 0s 4ms/step
Confusion Matrix (Output 2 - Classification):
[[163  53]
 [ 36  24]]


In [35]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output3_test = model.predict(X_test_normalized)[2]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output3_test_binary = np.round(y_pred_output3_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output3 = confusion_matrix(y_test_output3, y_pred_output3_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 3 - Classification):")
print(conf_matrix_output3)

9/9 [==============================] - 0s 5ms/step
Confusion Matrix (Output 3 - Classification):
[[177  33]
 [ 55  11]]


In [36]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output4_test = model.predict(X_test_normalized)[3]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output4_test_binary = np.round(y_pred_output4_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output4 = confusion_matrix(y_test_output4, y_pred_output4_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 4 - Classification):")
print(conf_matrix_output4)

9/9 [==============================] - 0s 5ms/step
Confusion Matrix (Output 4 - Classification):
[[177  24]
 [ 65  10]]


In [37]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output5_test = model.predict(X_test_normalized)[4]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output5_test_binary = np.round(y_pred_output5_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output5 = confusion_matrix(y_test_output5, y_pred_output5_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 5 - Classification):")
print(conf_matrix_output5)

9/9 [==============================] - 0s 4ms/step
Confusion Matrix (Output 5 - Classification):
[[160  41]
 [ 64  11]]
