## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Importing Dataset

In [3]:
dataset = pd.read_csv('./data/csv_experiments.csv')

In [4]:
dataset

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web02_00000  2019-04-26 07:07:27.543115   
1              1  zoo_web02_00001  2019-04-26 07:08:55.607184   
2              2  zoo_web02_00002  2019-04-26 07:10:24.541172   
3              3  zoo_web02_00003  2019-04-26 07:11:52.621173   
4              4  zoo_web02_00004  2019-04-26 07:13:20.620731   
...          ...              ...                         ...   
1595        1595  zoo_web02_01595  2019-04-27 22:20:15.376194   
1596        1596  zoo_web02_01596  2019-04-27 22:21:44.072224   
1597        1597  zoo_web02_01597  2019-04-27 22:23:13.746489   
1598        1598  zoo_web02_01598  2019-04-27 22:24:42.580889   
1599        1599  zoo_web02_01599  2019-04-27 22:26:11.427110   

                 experiment_stop  \
0     2019-04-26 07:08:27.673753   
1     2019-04-26 07:09:55.674753   
2     2019-04-26 07:11:24.602837   
3     2019-04-26 07:12:52.682799   
4     2019-04-26 07:14:20.703846   
...                          ...   
1595  2019-04-27 22:21:15.437489   
1596  2019-04-27 22:22:44.129055   
1597  2019-04-27 22:24:13.807803   
1598  2019-04-27 22:25:42.642429   
1599  2019-04-27 22:27:11.489061   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             43234.0   
1                                             43158.0   
2                                             43258.0   
3                                             44024.0   
4                                             43368.0   
...                                               ...   
1595                                            222.0   
1596                                            220.0   
1597                                            220.0   
1598                                            220.0   
1599                                            217.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             1.0   
1                                             1.0   
2                                             1.0   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                        /   
1                                        /   
2                                        /   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
... 

## Removing columns whose entire column is zero

In [5]:
def all_entries_nonzero(column):
    return (column != 0).any()

columns_to_drop = dataset.columns[~dataset.apply(all_entries_nonzero)]
dataset_new = dataset.drop(columns_to_drop, axis=1)


In [6]:
dataset_new

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web02_00000  2019-04-26 07:07:27.543115   
1              1  zoo_web02_00001  2019-04-26 07:08:55.607184   
2              2  zoo_web02_00002  2019-04-26 07:10:24.541172   
3              3  zoo_web02_00003  2019-04-26 07:11:52.621173   
4              4  zoo_web02_00004  2019-04-26 07:13:20.620731   
...          ...              ...                         ...   
1595        1595  zoo_web02_01595  2019-04-27 22:20:15.376194   
1596        1596  zoo_web02_01596  2019-04-27 22:21:44.072224   
1597        1597  zoo_web02_01597  2019-04-27 22:23:13.746489   
1598        1598  zoo_web02_01598  2019-04-27 22:24:42.580889   
1599        1599  zoo_web02_01599  2019-04-27 22:26:11.427110   

                 experiment_stop  \
0     2019-04-26 07:08:27.673753   
1     2019-04-26 07:09:55.674753   
2     2019-04-26 07:11:24.602837   
3     2019-04-26 07:12:52.682799   
4     2019-04-26 07:14:20.703846   
...                          ...   
1595  2019-04-27 22:21:15.437489   
1596  2019-04-27 22:22:44.129055   
1597  2019-04-27 22:24:13.807803   
1598  2019-04-27 22:25:42.642429   
1599  2019-04-27 22:27:11.489061   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             43234.0   
1                                             43158.0   
2                                             43258.0   
3                                             44024.0   
4                                             43368.0   
...                                               ...   
1595                                            222.0   
1596                                            220.0   
1597                                            220.0   
1598                                            220.0   
1599                                            217.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             1.0   
1                                             1.0   
2                                             1.0   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                        /   
1                                        /   
2                                        /   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
... 

# Checking for any Null values in dataset


In [7]:
dataset_new = dataset_new.replace('', np.nan)
dataset_new.isnull().sum()

Unnamed: 0                                          0
experiment_name                                     0
experiment_start                                    0
experiment_stop                                     0
metric__mp.input.vdu01.0__ab_completed_requests    30
                                                   ..
param__mp__mp.output__address                       0
param__mp__mp.output__connection_point              0
param__mp__mp.output__container                     0
param__mp__mp.output__name                          0
run_id                                              0
Length: 77, dtype: int64

In [8]:
dataset_new = dataset_new.dropna(axis=1, how='all')
dataset_new.isnull().sum()

Unnamed: 0                                          0
experiment_name                                     0
experiment_start                                    0
experiment_stop                                     0
metric__mp.input.vdu01.0__ab_completed_requests    30
                                                   ..
param__mp__mp.output__address                       0
param__mp__mp.output__connection_point              0
param__mp__mp.output__container                     0
param__mp__mp.output__name                          0
run_id                                              0
Length: 67, dtype: int64

In [9]:
dataset_new

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_web02_00000  2019-04-26 07:07:27.543115   
1              1  zoo_web02_00001  2019-04-26 07:08:55.607184   
2              2  zoo_web02_00002  2019-04-26 07:10:24.541172   
3              3  zoo_web02_00003  2019-04-26 07:11:52.621173   
4              4  zoo_web02_00004  2019-04-26 07:13:20.620731   
...          ...              ...                         ...   
1595        1595  zoo_web02_01595  2019-04-27 22:20:15.376194   
1596        1596  zoo_web02_01596  2019-04-27 22:21:44.072224   
1597        1597  zoo_web02_01597  2019-04-27 22:23:13.746489   
1598        1598  zoo_web02_01598  2019-04-27 22:24:42.580889   
1599        1599  zoo_web02_01599  2019-04-27 22:26:11.427110   

                 experiment_stop  \
0     2019-04-26 07:08:27.673753   
1     2019-04-26 07:09:55.674753   
2     2019-04-26 07:11:24.602837   
3     2019-04-26 07:12:52.682799   
4     2019-04-26 07:14:20.703846   
...                          ...   
1595  2019-04-27 22:21:15.437489   
1596  2019-04-27 22:22:44.129055   
1597  2019-04-27 22:24:13.807803   
1598  2019-04-27 22:25:42.642429   
1599  2019-04-27 22:27:11.489061   

      metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             43234.0   
1                                             43158.0   
2                                             43258.0   
3                                             44024.0   
4                                             43368.0   
...                                               ...   
1595                                            222.0   
1596                                            220.0   
1597                                            220.0   
1598                                            220.0   
1599                                            217.0   

      metric__mp.input.vdu01.0__ab_concurrent_lvl  \
0                                             1.0   
1                                             1.0   
2                                             1.0   
3                                             1.0   
4                                             1.0   
...                                           ...   
1595                                          1.0   
1596                                          1.0   
1597                                          1.0   
1598                                          1.0   
1599                                          1.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

     metric__mp.input.vdu01.0__ab_doc_path  \
0                                        /   
1                                        /   
2                                        /   
3                                        /   
4                                        /   
...                                    ...   
1595                            /bunny.mp4   
1596                            /bunny.mp4   
1597                            /bunny.mp4   
1598                            /bunny.mp4   
1599                            /bunny.mp4   

      metric__mp.input.vdu01.0__ab_failed_requests  \
0                                              0.0   
1                                              0.0   
2                                              0.0   
3                                              0.0   
4                                              0.0   
... 

In [10]:
def all_values_same(column):
    return column.nunique() == 1

columns_to_drop = dataset_new.columns[dataset_new.apply(all_values_same)]
dataset_new = dataset_new.drop(columns_to_drop, axis=1)

In [11]:
dataset_new.isnull().sum()

Unnamed: 0                                                      0
experiment_name                                                 0
experiment_start                                                0
experiment_stop                                                 0
metric__mp.input.vdu01.0__ab_completed_requests                30
metric__mp.input.vdu01.0__ab_doc_length                        30
metric__mp.input.vdu01.0__ab_doc_path                          30
metric__mp.input.vdu01.0__ab_html_transfer_byte                30
metric__mp.input.vdu01.0__ab_mean_time_per_request             30
metric__mp.input.vdu01.0__ab_request_per_second                30
metric__mp.input.vdu01.0__ab_rt_percentiles_csv                30
metric__mp.input.vdu01.0__ab_time_used_s                       30
metric__mp.input.vdu01.0__ab_total_transfer_byte               30
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    30
metric__mp.input.vdu01.0__stat__data__rx_bytes                  0
metric__mp

In [12]:
dataset_new = dataset_new.dropna()

In [13]:
dataset_new.isnull().sum()

Unnamed: 0                                                     0
experiment_name                                                0
experiment_start                                               0
experiment_stop                                                0
metric__mp.input.vdu01.0__ab_completed_requests                0
metric__mp.input.vdu01.0__ab_doc_length                        0
metric__mp.input.vdu01.0__ab_doc_path                          0
metric__mp.input.vdu01.0__ab_html_transfer_byte                0
metric__mp.input.vdu01.0__ab_mean_time_per_request             0
metric__mp.input.vdu01.0__ab_request_per_second                0
metric__mp.input.vdu01.0__ab_rt_percentiles_csv                0
metric__mp.input.vdu01.0__ab_time_used_s                       0
metric__mp.input.vdu01.0__ab_total_transfer_byte               0
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    0
metric__mp.input.vdu01.0__stat__data__rx_bytes                 0
metric__mp.input.vdu01.0_

In [14]:
dataset_new.columns

Index(['Unnamed: 0', 'experiment_name', 'experiment_start', 'experiment_stop',
       'metric__mp.input.vdu01.0__ab_completed_requests',
       'metric__mp.input.vdu01.0__ab_doc_length',
       'metric__mp.input.vdu01.0__ab_doc_path',
       'metric__mp.input.vdu01.0__ab_html_transfer_byte',
       'metric__mp.input.vdu01.0__ab_mean_time_per_request',
       'metric__mp.input.vdu01.0__ab_request_per_second',
       'metric__mp.input.vdu01.0__ab_rt_percentiles_csv',
       'metric__mp.input.vdu01.0__ab_time_used_s',
       'metric__mp.input.vdu01.0__ab_total_transfer_byte',
       'metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
  

In [15]:
dataset_new = dataset_new.drop(['Unnamed: 0','experiment_name', 'experiment_start', 'experiment_stop', 'metric__mp.input.vdu01.0__ab_doc_path', 'metric__mp.input.vdu01.0__ab_rt_percentiles_csv', 'param__func__mp.input__cmd_start', 'param__header__all__config_id', 'param__header__all__repetition', 'run_id'],axis=1)
dataset_new.columns

Index(['metric__mp.input.vdu01.0__ab_completed_requests',
       'metric__mp.input.vdu01.0__ab_doc_length',
       'metric__mp.input.vdu01.0__ab_html_transfer_byte',
       'metric__mp.input.vdu01.0__ab_mean_time_per_request',
       'metric__mp.input.vdu01.0__ab_request_per_second',
       'metric__mp.input.vdu01.0__ab_time_used_s',
       'metric__mp.input.vdu01.0__ab_total_transfer_byte',
       'metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__rx_bytes',
       'metric__mp.output.vdu01.0__stat__data__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__tx_bytes',
       'met

In [16]:
dataset_new.dtypes

metric__mp.input.vdu01.0__ab_completed_requests                float64
metric__mp.input.vdu01.0__ab_doc_length                        float64
metric__mp.input.vdu01.0__ab_html_transfer_byte                float64
metric__mp.input.vdu01.0__ab_mean_time_per_request             float64
metric__mp.input.vdu01.0__ab_request_per_second                float64
metric__mp.input.vdu01.0__ab_time_used_s                       float64
metric__mp.input.vdu01.0__ab_total_transfer_byte               float64
metric__mp.input.vdu01.0__ab_transfer_rate_kbyte_per_second    float64
metric__mp.input.vdu01.0__stat__data__rx_bytes                 float64
metric__mp.input.vdu01.0__stat__data__rx_packets               float64
metric__mp.input.vdu01.0__stat__data__tx_bytes                 float64
metric__mp.input.vdu01.0__stat__data__tx_packets               float64
metric__mp.input.vdu01.0__stat__eth0__rx_bytes                 float64
metric__mp.input.vdu01.0__stat__eth0__rx_packets               float64
metric

In [17]:
X = dataset_new.iloc[:, :-2].values
y = dataset_new.iloc[:, -2:].values

In [18]:
print(y)

[[1.00e-01 6.40e+01]
 [1.00e-01 6.40e+01]
 [1.00e-01 6.40e+01]
 ...
 [1.00e+00 5.12e+02]
 [1.00e+00 5.12e+02]
 [1.00e+00 5.12e+02]]


## One Hot Encoding mem_max variable

In [19]:
data = dataset_new['param__func__de.upb.lb-haproxy.0.1__mem_max']
encoded_data = pd.get_dummies(data, columns=['param__func__de.upb.lb-haproxy.0.1__mem_max'])
dataset_new = dataset_new.drop('param__func__de.upb.lb-haproxy.0.1__mem_max', axis = 1)
dataset_new = pd.concat([dataset_new, encoded_data], axis=1)
dataset_new

metric__mp.input.vdu01.0__ab_completed_requests  \
0                                             43234.0   
1                                             43158.0   
2                                             43258.0   
3                                             44024.0   
4                                             43368.0   
...                                               ...   
1595                                            222.0   
1596                                            220.0   
1597                                            220.0   
1598                                            220.0   
1599                                            217.0   

      metric__mp.input.vdu01.0__ab_doc_length  \
0                                         0.0   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   
...                                       ...   
1595                              318388586.0   
1596                              318388586.0   
1597                              318388586.0   
1598                              318388586.0   
1599                              318388586.0   

      metric__mp.input.vdu01.0__ab_html_transfer_byte  \
0                                        0.000000e+00   
1                                        0.000000e+00   
2                                        0.000000e+00   
3                                        0.000000e+00   
4                                        0.000000e+00   
...                                               ...   
1595                                     7.068227e+10   
1596                                     7.004549e+10   
1597                                     7.004549e+10   
1598                                     7.004549e+10   
1599                                     6.909032e+10   

      metric__mp.input.vdu01.0__ab_mean_time_per_request  \
0                                                 1.406    
1                                                 1.407    
2                                                 1.387    
3                                                 1.379    
4                                                 1.401    
...                                                 ...    
1595                                            270.290    
1596                                            273.860    
1597                                            273.364    
1598                                            273.654    
1599                                            277.395    

      metric__mp.input.vdu01.0__ab_request_per_second  \
0                                              711.04   
1                                              710.55   
2                                              720.97   
3                                              724.93   
4                                              713.67   
...                                               ...   
1595                                             3.70   
1596                                             3.65   
1597                                             3.66   
1598                                             3.65   
1599                                             3.60   

      metric__mp.input.vdu01.0__ab_time_used_s  \
0                                       60.804   
1                                       60.739   
2                                       60.000   
3                                       60.729   
4                                       60.768   
...                                        ...   
1595                                    60.004   
1596                                    60.249   
1597                                    60.140   
1598                                    60.204   
1599                                    60.195   

      metric__mp.input.vdu01.0__ab_total

In [20]:
y= dataset_new.iloc[:, -5:].values
print(y)

[[0.1 1.  0.  0.  0. ]
 [0.1 1.  0.  0.  0. ]
 [0.1 1.  0.  0.  0. ]
 ...
 [1.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  1. ]
 [1.  0.  0.  0.  1. ]]


## Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Separate the two output features
y_train_output1 = y_train[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_train_output2 = y_train[:, -4]  # Second column for binary classification

y_train_output3 = y_train[:, -3]
y_train_output4 = y_train[:, -2]
y_train_output5 = y_train[:, -1]

y_test_output1 = y_test[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_test_output2 = y_test[:, -4]  # Second column for binary classification

y_test_output3 = y_test[:, -3]
y_test_output4 = y_test[:, -2]
y_test_output5 = y_test[:, -1]

In [22]:
print(y_train_output1)

[0.9 0.2 0.8 ... 0.8 0.4 0.5]


## Feature Scaling

In [23]:
from sklearn.preprocessing import MinMaxScaler

# Normalize input features
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)



In [24]:
print(X_train_normalized)

[[9.63272172e-01 0.00000000e+00 0.00000000e+00 ... 5.20904036e-01
  9.59110403e-01 9.55758201e-01]
 [3.47422564e-01 0.00000000e+00 0.00000000e+00 ... 1.27579711e-01
  3.27692771e-01 3.20188386e-01]
 [9.74340247e-01 0.00000000e+00 0.00000000e+00 ... 5.33673155e-01
  9.74013310e-01 9.72990670e-01]
 ...
 [9.81177668e-01 0.00000000e+00 0.00000000e+00 ... 5.30598152e-01
  9.76333678e-01 9.72381880e-01]
 [2.71942876e-04 1.00000000e+00 3.94618834e-01 ... 3.42970588e-01
  1.05995901e-01 1.33579364e-01]
 [3.65180434e-04 1.00000000e+00 5.02242152e-01 ... 4.64110000e-01
  1.41649981e-01 1.79180569e-01]]


In [25]:
print(type(y_train_output1))
print(type(y_train_output2))
print(type(y_train_output3))
print(type(y_train_output4))
print(type(y_train_output5))

print(type(y_test_output1))
print(type(y_test_output2))
print(type(y_test_output3))
print(type(y_test_output4))
print(type(y_test_output5))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [26]:
print(X_train_normalized.shape)
print(y_train_output1.shape)
print(y_train_output2.shape)
print(y_train_output3.shape)
print(y_train_output4.shape)
print(y_train_output5.shape)

print(y_test_output1.shape)
print(y_test_output2.shape)
print(y_test_output3.shape)
print(y_test_output4.shape)
print(y_test_output5.shape)

(1256, 32)
(1256,)
(1256,)
(1256,)
(1256,)
(1256,)
(314,)
(314,)
(314,)
(314,)
(314,)


## Building Model

In [27]:
input_shape = (32,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=64, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dense(units=32, activation='relu')(x)
output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification

output_3 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_3')(x)  # Output 2: Classification
output_4 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_4')(x)  # Output 2: Classification
output_5 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_5')(x)  # Output 2: Classification

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2, output_3, output_4, output_5])

# Check the model output names
print("Model Output Names:", model.output_names)  


Model Output Names: ['output_1', 'output_2', 'output_3', 'output_4', 'output_5']


In [28]:
model.compile(
    loss={
        'output_1': 'mean_squared_error',  # Regression loss function
        'output_2': 'binary_crossentropy',  # Categorical classification loss function
        'output_3': 'binary_crossentropy',
        'output_4': 'binary_crossentropy',
        'output_5': 'binary_crossentropy',
    },
    optimizer='adam',
    metrics={
        'output_1': ['mae', 'mse'],
        'output_2': 'accuracy',
        'output_3': 'accuracy',
        'output_4': 'accuracy',
        'output_5': 'accuracy',
    }
)

model.fit(X_train_normalized, {'output_1': y_train_output1, 'output_2': y_train_output2, 'output_3': y_train_output3, 'output_4': y_train_output4, 'output_5': y_train_output5},
          validation_data=(X_test_normalized, {'output_1': y_test_output1, 'output_2': y_test_output2, 'output_3': y_test_output3, 'output_4': y_test_output4, 'output_5': y_test_output5}),
          epochs=50, batch_size=32)



Epoch 1/50
40/40 [==============================] - 6s 39ms/step - loss: 2.6507 - output_1_loss: 0.0956 - output_2_loss: 0.6133 - output_3_loss: 0.5892 - output_4_loss: 0.6430 - output_5_loss: 0.7095 - output_1_mae: 0.2222 - output_1_mse: 0.0956 - output_2_accuracy: 0.7548 - output_3_accuracy: 0.7492 - output_4_accuracy: 0.6584 - output_5_accuracy: 0.4124 - val_loss: 2.3521 - val_output_1_loss: 0.0166 - val_output_2_loss: 0.5746 - val_output_3_loss: 0.5806 - val_output_4_loss: 0.5563 - val_output_5_loss: 0.6240 - val_output_1_mae: 0.1047 - val_output_1_mse: 0.0166 - val_output_2_accuracy: 0.7389 - val_output_3_accuracy: 0.7452 - val_output_4_accuracy: 0.7643 - val_output_5_accuracy: 0.7516
Epoch 2/50
40/40 [==============================] - 0s 9ms/step - loss: 2.3289 - output_1_loss: 0.0250 - output_2_loss: 0.5702 - output_3_loss: 0.5744 - output_4_loss: 0.5765 - output_5_loss: 0.5827 - output_1_mae: 0.1223 - output_1_mse: 0.0250 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500 

Epoch 13/50
40/40 [==============================] - 0s 9ms/step - loss: 2.2559 - output_1_loss: 0.0126 - output_2_loss: 0.5561 - output_3_loss: 0.5601 - output_4_loss: 0.5653 - output_5_loss: 0.5619 - output_1_mae: 0.0825 - output_1_mse: 0.0126 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500 - output_4_accuracy: 0.7436 - output_5_accuracy: 0.7524 - val_loss: 2.2580 - val_output_1_loss: 0.0133 - val_output_2_loss: 0.5676 - val_output_3_loss: 0.5659 - val_output_4_loss: 0.5524 - val_output_5_loss: 0.5589 - val_output_1_mae: 0.0751 - val_output_1_mse: 0.0133 - val_output_2_accuracy: 0.7389 - val_output_3_accuracy: 0.7452 - val_output_4_accuracy: 0.7643 - val_output_5_accuracy: 0.7516
Epoch 14/50
40/40 [==============================] - 0s 8ms/step - loss: 2.2534 - output_1_loss: 0.0128 - output_2_loss: 0.5534 - output_3_loss: 0.5595 - output_4_loss: 0.5678 - output_5_loss: 0.5600 - output_1_mae: 0.0826 - output_1_mse: 0.0128 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500

Epoch 25/50
40/40 [==============================] - 0s 8ms/step - loss: 2.2509 - output_1_loss: 0.0121 - output_2_loss: 0.5517 - output_3_loss: 0.5601 - output_4_loss: 0.5695 - output_5_loss: 0.5576 - output_1_mae: 0.0805 - output_1_mse: 0.0121 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500 - output_4_accuracy: 0.7436 - output_5_accuracy: 0.7524 - val_loss: 2.2535 - val_output_1_loss: 0.0128 - val_output_2_loss: 0.5684 - val_output_3_loss: 0.5635 - val_output_4_loss: 0.5510 - val_output_5_loss: 0.5580 - val_output_1_mae: 0.0797 - val_output_1_mse: 0.0128 - val_output_2_accuracy: 0.7389 - val_output_3_accuracy: 0.7452 - val_output_4_accuracy: 0.7643 - val_output_5_accuracy: 0.7516
Epoch 26/50
40/40 [==============================] - 0s 8ms/step - loss: 2.2457 - output_1_loss: 0.0116 - output_2_loss: 0.5526 - output_3_loss: 0.5587 - output_4_loss: 0.5641 - output_5_loss: 0.5588 - output_1_mae: 0.0765 - output_1_mse: 0.0116 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500

Epoch 37/50
40/40 [==============================] - 0s 8ms/step - loss: 2.2406 - output_1_loss: 0.0115 - output_2_loss: 0.5500 - output_3_loss: 0.5572 - output_4_loss: 0.5643 - output_5_loss: 0.5576 - output_1_mae: 0.0766 - output_1_mse: 0.0115 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500 - output_4_accuracy: 0.7436 - output_5_accuracy: 0.7524 - val_loss: 2.2613 - val_output_1_loss: 0.0187 - val_output_2_loss: 0.5697 - val_output_3_loss: 0.5616 - val_output_4_loss: 0.5544 - val_output_5_loss: 0.5569 - val_output_1_mae: 0.1007 - val_output_1_mse: 0.0187 - val_output_2_accuracy: 0.7389 - val_output_3_accuracy: 0.7452 - val_output_4_accuracy: 0.7643 - val_output_5_accuracy: 0.7516
Epoch 38/50
40/40 [==============================] - 0s 8ms/step - loss: 2.2384 - output_1_loss: 0.0116 - output_2_loss: 0.5496 - output_3_loss: 0.5551 - output_4_loss: 0.5656 - output_5_loss: 0.5565 - output_1_mae: 0.0785 - output_1_mse: 0.0116 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500

Epoch 49/50
40/40 [==============================] - 0s 8ms/step - loss: 2.2211 - output_1_loss: 0.0114 - output_2_loss: 0.5453 - output_3_loss: 0.5522 - output_4_loss: 0.5614 - output_5_loss: 0.5506 - output_1_mae: 0.0772 - output_1_mse: 0.0114 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500 - output_4_accuracy: 0.7436 - output_5_accuracy: 0.7524 - val_loss: 2.2467 - val_output_1_loss: 0.0097 - val_output_2_loss: 0.5652 - val_output_3_loss: 0.5622 - val_output_4_loss: 0.5556 - val_output_5_loss: 0.5539 - val_output_1_mae: 0.0642 - val_output_1_mse: 0.0097 - val_output_2_accuracy: 0.7389 - val_output_3_accuracy: 0.7452 - val_output_4_accuracy: 0.7643 - val_output_5_accuracy: 0.7516
Epoch 50/50
40/40 [==============================] - 0s 9ms/step - loss: 2.2352 - output_1_loss: 0.0111 - output_2_loss: 0.5497 - output_3_loss: 0.5548 - output_4_loss: 0.5645 - output_5_loss: 0.5551 - output_1_mae: 0.0775 - output_1_mse: 0.0111 - output_2_accuracy: 0.7540 - output_3_accuracy: 0.7500

In [29]:
# After the model is trained, you can make predictions
y_pred_output1, y_pred_output2, y_pred_output3, y_pred_output4, y_pred_output5 = model.predict(X_test_normalized)

# For output_1 (Regression)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_output1 = mean_absolute_error(y_test_output1, y_pred_output1)
mse_output1 = mean_squared_error(y_test_output1, y_pred_output1)
r2_output1 = r2_score(y_test_output1, y_pred_output1)

print("Output 1 - Mean Absolute Error:", mae_output1)
print("Output 1 - Mean Squared Error:", mse_output1)
print("Output 1 - R^2 Score:", r2_output1)

# For output_2 to output_5 (Classification)
from sklearn.metrics import accuracy_score, confusion_matrix

for i in range(4):
    cm = confusion_matrix(y_test_output2, np.round(y_pred_output2))
    accuracy = accuracy_score(y_test_output2, np.round(y_pred_output2))
    print(f"Confusion Matrix for Classification Output {i+2}:\n{cm}")
    print(f"Accuracy Score for Classification Output {i+2}: {accuracy}")




10/10 [==============================] - 0s 2ms/step
Output 1 - Mean Absolute Error: 0.07428528819778923
Output 1 - Mean Squared Error: 0.012819687232182343
Output 1 - R^2 Score: 0.8464790911024679
Confusion Matrix for Classification Output 2:
[[232   0]
 [ 82   0]]
Accuracy Score for Classification Output 2: 0.7388535031847133
Confusion Matrix for Classification Output 3:
[[232   0]
 [ 82   0]]
Accuracy Score for Classification Output 3: 0.7388535031847133
Confusion Matrix for Classification Output 4:
[[232   0]
 [ 82   0]]
Accuracy Score for Classification Output 4: 0.7388535031847133
Confusion Matrix for Classification Output 5:
[[232   0]
 [ 82   0]]
Accuracy Score for Classification Output 5: 0.7388535031847133


In [30]:
y_test1 = y_test[:,0]

rounded_y_pred = y_pred_output1.reshape(len(y_pred_output1), 1).round(1)

# Reshape y_test1 to a column vector
y_test1_reshaped = y_test1.reshape(len(y_test1), 1)

# Concatenate both arrays side by side (along axis 1)
result = np.concatenate((rounded_y_pred, y_test1_reshaped), axis=1)
np.set_printoptions(precision=1)
print(result)

[[0.3 0.3]
 [0.6 0.8]
 [0.9 0.9]
 [0.4 0.4]
 [0.3 0.3]
 [0.4 0.4]
 [0.5 0.5]
 [0.8 0.8]
 [0.7 0.9]
 [0.4 0.4]
 [0.2 0.3]
 [0.7 1. ]
 [0.4 0.4]
 [0.6 0.8]
 [0.1 0.1]
 [0.7 0.6]
 [0.6 0.7]
 [0.1 0.1]
 [0.8 0.9]
 [0.7 1. ]
 [0.6 0.6]
 [0.2 0.2]
 [0.2 0.3]
 [0.6 0.6]
 [0.1 0.1]
 [0.9 1. ]
 [0.6 0.7]
 [0.6 0.5]
 [0.7 0.7]
 [0.3 0.3]
 [0.7 0.9]
 [0.1 0.1]
 [0.4 0.5]
 [0.1 0.1]
 [0.6 0.5]
 [0.6 1. ]
 [0.8 0.9]
 [0.4 0.5]
 [0.6 0.7]
 [0.1 0.1]
 [0.3 0.3]
 [0.7 0.7]
 [0.1 0.1]
 [0.7 0.8]
 [0.2 0.2]
 [0.2 0.3]
 [0.1 0.1]
 [0.4 0.4]
 [0.6 1. ]
 [0.5 0.5]
 [0.7 0.7]
 [0.6 0.6]
 [0.6 0.8]
 [1.  1. ]
 [0.9 1. ]
 [0.5 0.5]
 [0.7 0.8]
 [0.2 0.2]
 [0.1 0.1]
 [0.2 0.3]
 [0.9 1. ]
 [0.6 0.6]
 [0.2 0.2]
 [0.3 0.3]
 [0.3 0.3]
 [0.7 0.7]
 [0.6 0.6]
 [0.6 0.7]
 [0.7 0.9]
 [0.2 0.2]
 [0.5 0.4]
 [0.5 0.5]
 [0.7 0.7]
 [0.7 0.8]
 [0.7 0.7]
 [0.7 0.6]
 [0.3 0.3]
 [0.2 0.2]
 [0.4 0.4]
 [0.7 0.7]
 [0.1 0.2]
 [0.6 0.7]
 [0.2 0.2]
 [0.6 0.8]
 [0.1 0.1]
 [0.4 0.4]
 [0.7 0.7]
 [0.2 0.3]
 [0.7 0.7]
 [0.2 0.2]
 [0.2 0.2]

## K-fold Cross Validation

In [31]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

num_folds = 5

# Initialize lists to store the evaluation metrics for each fold
mse_output1_list = []
accuracy_output2_list = []
accuracy_output3_list = []
accuracy_output4_list = []
accuracy_output5_list = []

# Create the KFold object
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)


# Create the model
input_shape = (32,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=256, activation='relu')(inputs)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=256, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation

x = tf.keras.layers.Dense(units=128, activation='relu')(x)  # GELU activation
   

output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification
output_3 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_3')(x)
output_4 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_4')(x)
output_5 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_5')(x)

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2, output_3, output_4, output_5])

# Perform 5-fold cross-validation
for fold, (train_indices, val_indices) in enumerate(kfold.split(X_train_normalized)):
    print(f"Fold {fold+1}/{num_folds}")
    
    # Split the data into training and validation sets for this fold
    X_train_fold = X_train_normalized[train_indices]
    X_val_fold = X_train_normalized[val_indices]
    y_train_output1_fold = y_train_output1[train_indices]
    y_train_output2_fold = y_train_output2[train_indices]
    y_train_output3_fold = y_train_output3[train_indices]
    y_train_output4_fold = y_train_output4[train_indices]
    y_train_output5_fold = y_train_output5[train_indices]
    
    y_val_output1_fold = y_train_output1[val_indices]
    y_val_output2_fold = y_train_output2[val_indices]
    y_val_output3_fold = y_train_output3[val_indices]
    y_val_output4_fold = y_train_output4[val_indices]
    y_val_output5_fold = y_train_output5[val_indices]
    
    
    # Compile the model
    model.compile(
        loss={
            'output_1': 'mean_squared_error',  # Regression loss function
            'output_2': 'binary_crossentropy',  # classification loss function
            'output_3': 'binary_crossentropy',
            'output_4': 'binary_crossentropy',
            'output_5': 'binary_crossentropy',
        },
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        metrics={
            'output_1': ['mae', 'mse'],
            'output_2': 'accuracy',
            'output_3': 'accuracy',
            'output_4': 'accuracy',
            'output_5': 'accuracy',
        }
    )
    

    # Train the model
    model.fit(X_train_fold, {'output_1': y_train_output1_fold, 'output_2': y_train_output2_fold, 'output_3': y_train_output3_fold, 'output_4': y_train_output4_fold, 'output_5': y_train_output5_fold},
          epochs=100, batch_size=32, verbose=0)

    
    # Evaluate the model on validation data for this fold
    results = model.evaluate(X_val_fold, {'output_1': y_val_output1_fold, 'output_2': y_val_output2_fold, 'output_3': y_val_output3_fold, 'output_4': y_val_output4_fold, 'output_5': y_val_output5_fold})
#     print("Results:", results)
    
    mse_output1_list.append(results[2])  # Index 2 corresponds to MSE for 'output_1'
    accuracy_output2_list.append(results[8])  # Index 5 corresponds to accuracy for 'output_2'
    accuracy_output3_list.append(results[9])  # Index 8 corresponds to accuracy for 'output_3'
    accuracy_output4_list.append(results[10])  # Index 11 corresponds to accuracy for 'output_4'
    accuracy_output5_list.append(results[11])  # Index 14 corresponds to accuracy for 'output_5'




Fold 1/5
8/8 [==============================] - 1s 7ms/step - loss: 3.3475 - output_1_loss: 0.0126 - output_2_loss: 0.9186 - output_3_loss: 0.6717 - output_4_loss: 0.9733 - output_5_loss: 0.7712 - output_1_mae: 0.0848 - output_1_mse: 0.0126 - output_2_accuracy: 0.7063 - output_3_accuracy: 0.7222 - output_4_accuracy: 0.6905 - output_5_accuracy: 0.6905
Fold 2/5
8/8 [==============================] - 1s 7ms/step - loss: 4.3864 - output_1_loss: 0.0116 - output_2_loss: 1.4341 - output_3_loss: 0.9190 - output_4_loss: 1.1219 - output_5_loss: 0.8998 - output_1_mae: 0.0786 - output_1_mse: 0.0116 - output_2_accuracy: 0.6693 - output_3_accuracy: 0.7291 - output_4_accuracy: 0.7012 - output_5_accuracy: 0.7371
Fold 3/5
8/8 [==============================] - 1s 7ms/step - loss: 3.2437 - output_1_loss: 0.0120 - output_2_loss: 0.7961 - output_3_loss: 0.9248 - output_4_loss: 0.7884 - output_5_loss: 0.7224 - output_1_mae: 0.0798 - output_1_mse: 0.0120 - output_2_accuracy: 0.7331 - output_3_accuracy: 0.74

In [32]:
# Calculate the mean and standard deviation of evaluation metrics across all folds
mean_mse_output1 = np.mean(mse_output1_list)
mean_accuracy_output2 = np.mean(accuracy_output2_list)
mean_accuracy_output3 = np.mean(accuracy_output3_list)
mean_accuracy_output4 = np.mean(accuracy_output4_list)
mean_accuracy_output5 = np.mean(accuracy_output5_list)


std_mse_output1 = np.std(mse_output1_list)
std_accuracy_output2 = np.std(accuracy_output2_list)
std_accuracy_output3 = np.std(accuracy_output3_list)
std_accuracy_output4 = np.std(accuracy_output4_list)
std_accuracy_output5 = np.std(accuracy_output5_list)

# For regression task (output_1) - Calculate R-squared (R^2) score
y_true_output1 = np.concatenate([y_train_output1, y_test_output1])
y_pred_output1 = model.predict(np.concatenate([X_train_normalized, X_test_normalized]))[0]
r2_output1 = r2_score(y_true_output1, y_pred_output1)

print("Mean MSE (Output 1):", mean_mse_output1)
print("Mean Accuracy (Output 2):", mean_accuracy_output2)
print("Mean Accuracy (Output 3):", mean_accuracy_output3)
print("Mean Accuracy (Output 4):", mean_accuracy_output4)
print("Mean Accuracy (Output 5):", mean_accuracy_output5)

print("Standard Deviation MSE (Output 1):", std_mse_output1)
print("Standard Deviation Accuracy (Output 2):", std_accuracy_output2)
print("Standard Deviation Accuracy (Output 3):", std_accuracy_output3)
print("Standard Deviation Accuracy (Output 4):", std_accuracy_output4)
print("Standard Deviation Accuracy (Output 5):", std_accuracy_output5)

print("R^2 Score (Output 1 - Regression):", r2_output1)


50/50 [==============================] - 0s 4ms/step
Mean MSE (Output 1): 0.8758182406425477
Mean Accuracy (Output 2): 0.7340985417366028
Mean Accuracy (Output 3): 0.753209388256073
Mean Accuracy (Output 4): 0.7452665567398071
Mean Accuracy (Output 5): 0.7420793056488038
Standard Deviation MSE (Output 1): 0.3023042044495677
Standard Deviation Accuracy (Output 2): 0.04352087968291706
Standard Deviation Accuracy (Output 3): 0.029472236321760575
Standard Deviation Accuracy (Output 4): 0.04929335691173353
Standard Deviation Accuracy (Output 5): 0.033932693663954634
R^2 Score (Output 1 - Regression): 0.9107057424165681


In [33]:
# 1. Compare Regression Output with Original Test Values

# Predict using the trained model on the test data for the regression output (output_1)
y_pred_output1_test = model.predict(X_test_normalized)[0]

# Reshape the predictions and original test values to match for comparison
y_pred_output1_test = y_pred_output1_test.flatten()

# Convert both arrays to the same data type (e.g., float64) for comparison
y_test_output1 = y_test_output1.astype(np.float64)
y_pred_output1_test = y_pred_output1_test.astype(np.float64)

# Stack the original test values and predicted values horizontally
comparison_output1 = np.column_stack((y_test_output1, y_pred_output1_test))

# Print the original test values and predicted values side by side
print("Original Test Values (Output 1) vs. Predicted Values (Output 1):")
print(comparison_output1)

10/10 [==============================] - 0s 4ms/step
Original Test Values (Output 1) vs. Predicted Values (Output 1):
[[ 0.3  0.3]
 [ 0.8  0.8]
 [ 0.9  0.8]
 [ 0.4  0.4]
 [ 0.3  0.5]
 [ 0.4  0.4]
 [ 0.5  0.5]
 [ 0.8  1. ]
 [ 0.9  0.9]
 [ 0.4  0.4]
 [ 0.3  0.4]
 [ 1.   0.9]
 [ 0.4  0.3]
 [ 0.8  0.7]
 [ 0.1  0.1]
 [ 0.6  0.7]
 [ 0.7  0.7]
 [ 0.1  0.2]
 [ 0.9  0.9]
 [ 1.   0.7]
 [ 0.6  0.4]
 [ 0.2  0.1]
 [ 0.3  0.3]
 [ 0.6  0.6]
 [ 0.1  0.1]
 [ 1.   1. ]
 [ 0.7  0.8]
 [ 0.5  0.6]
 [ 0.7  0.7]
 [ 0.3  0.2]
 [ 0.9  0.9]
 [ 0.1  0.1]
 [ 0.5  0.5]
 [ 0.1  0.1]
 [ 0.5  0.6]
 [ 1.   0.8]
 [ 0.9  0.9]
 [ 0.5  0.5]
 [ 0.7  0.7]
 [ 0.1  0.2]
 [ 0.3  0.4]
 [ 0.7  0.5]
 [ 0.1  0.2]
 [ 0.8  0.7]
 [ 0.2  0.3]
 [ 0.3  0.3]
 [ 0.1  0.2]
 [ 0.4  0.4]
 [ 1.   0.7]
 [ 0.5  0.5]
 [ 0.7  0.7]
 [ 0.6  0.6]
 [ 0.8  0.6]
 [ 1.   0.9]
 [ 1.   1. ]
 [ 0.5  0.6]
 [ 0.8  0.9]
 [ 0.2  0.2]
 [ 0.1  0. ]
 [ 0.3  0.4]
 [ 1.   0.9]
 [ 0.6  0.9]
 [ 0.2  0.3]
 [ 0.3  0.3]
 [ 0.3  0.3]
 [ 0.7  0.6]
 [ 0.6  0.6]
 [ 0.7  0.6

In [34]:
# 2. Generate Confusion Matrix for Classification

# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output2_test = model.predict(X_test_normalized)[1]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output2_test_binary = np.round(y_pred_output2_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output2 = confusion_matrix(y_test_output2, y_pred_output2_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 2 - Classification):")
print(conf_matrix_output2)

10/10 [==============================] - 0s 4ms/step
Confusion Matrix (Output 2 - Classification):
[[175  57]
 [ 55  27]]


In [35]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output3_test = model.predict(X_test_normalized)[2]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output3_test_binary = np.round(y_pred_output3_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output3 = confusion_matrix(y_test_output3, y_pred_output3_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 3 - Classification):")
print(conf_matrix_output3)

10/10 [==============================] - 0s 4ms/step
Confusion Matrix (Output 3 - Classification):
[[188  46]
 [ 55  25]]


In [36]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output4_test = model.predict(X_test_normalized)[3]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output4_test_binary = np.round(y_pred_output4_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output4 = confusion_matrix(y_test_output4, y_pred_output4_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 4 - Classification):")
print(conf_matrix_output4)

10/10 [==============================] - 0s 4ms/step
Confusion Matrix (Output 4 - Classification):
[[198  42]
 [ 53  21]]


In [37]:
# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output5_test = model.predict(X_test_normalized)[4]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output5_test_binary = np.round(y_pred_output5_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output5 = confusion_matrix(y_test_output5, y_pred_output5_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 5 - Classification):")
print(conf_matrix_output5)

10/10 [==============================] - 0s 4ms/step
Confusion Matrix (Output 5 - Classification):
[[184  52]
 [ 53  25]]
