## Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Importing Dataset

In [3]:
dataset = pd.read_csv('./data/csv_experiments.csv')

In [4]:
dataset

Unnamed: 0  experiment_name            experiment_start  \
0              0  zoo_sec01_00000  2019-05-10 14:34:58.787669   
1              1  zoo_sec01_00001  2019-05-10 14:37:45.155444   
2              2  zoo_sec01_00002  2019-05-10 14:40:30.377193   
3              3  zoo_sec01_00003  2019-05-10 14:43:15.109071   
4              4  zoo_sec01_00004  2019-05-10 14:45:59.170184   
...          ...              ...                         ...   
1595        1595  zoo_sec01_01595  2019-05-13 13:23:55.992925   
1596        1596  zoo_sec01_01596  2019-05-13 13:26:33.492290   
1597        1597  zoo_sec01_01597  2019-05-13 13:29:12.578989   
1598        1598  zoo_sec01_01598  2019-05-13 13:31:50.365057   
1599        1599  zoo_sec01_01599  2019-05-13 13:34:28.814379   

                 experiment_stop  \
0     2019-05-10 14:36:58.909504   
1     2019-05-10 14:39:45.276561   
2     2019-05-10 14:42:30.487209   
3     2019-05-10 14:45:15.230211   
4     2019-05-10 14:47:59.291305   
...                          ...   
1595  2019-05-13 13:25:56.110507   
1596  2019-05-13 13:28:33.602314   
1597  2019-05-13 13:31:12.689784   
1598  2019-05-13 13:33:50.475290   
1599  2019-05-13 13:36:28.934437   

      metric__mp.input.vdu01.0__stat__data__collisions  \
0                                                  0.0   
1                                                  0.0   
2                                                  0.0   
3                                                  0.0   
4                                                  0.0   
...                                                ...   
1595                                               0.0   
1596                                               0.0   
1597                                               0.0   
1598                                               0.0   
1599                                               0.0   

      metric__mp.input.vdu01.0__stat__data__multicast  \
0                                                 0.0   
1                                                 0.0   
2                                                 0.0   
3                                                 0.0   
4                                                 0.0   
...                                               ...   
1595                                              0.0   
1596                                              0.0   
1597                                              0.0   
1598                                              0.0   
1599                                              0.0   

      metric__mp.input.vdu01.0__stat__data__rx_bytes  \
0                                             1038.0   
1                                             1038.0   
2                                             1038.0   
3                                             1038.0   
4                                             1038.0   
...                                              ...   
1595                                          1038.0   
1596                                          1038.0   
1597                                           878.0   
1598                                          1038.0   
1599                                          1038.0   

      metric__mp.input.vdu01.0__stat__data__rx_compressed  \
0                                                   0.0     
1                                                   0.0     
2                                                   0.0     
3                                                   0.0     
4                                                   0.0     
...                                                 ...     
1595                                                0.0     
1596                                                0.0     
1597                                                0.0     
1598                                                0.0     
1599                                                0.0     

    

In [5]:
def all_entries_zero(column):
    return column.all() == 0

columns_to_drop = dataset.columns[dataset.apply(all_entries_zero)]
dataset_new = dataset.drop(columns_to_drop, axis=1)

In [6]:
dataset_new

experiment_name            experiment_start             experiment_stop  \
0     zoo_sec01_00000  2019-05-10 14:34:58.787669  2019-05-10 14:36:58.909504   
1     zoo_sec01_00001  2019-05-10 14:37:45.155444  2019-05-10 14:39:45.276561   
2     zoo_sec01_00002  2019-05-10 14:40:30.377193  2019-05-10 14:42:30.487209   
3     zoo_sec01_00003  2019-05-10 14:43:15.109071  2019-05-10 14:45:15.230211   
4     zoo_sec01_00004  2019-05-10 14:45:59.170184  2019-05-10 14:47:59.291305   
...               ...                         ...                         ...   
1595  zoo_sec01_01595  2019-05-13 13:23:55.992925  2019-05-13 13:25:56.110507   
1596  zoo_sec01_01596  2019-05-13 13:26:33.492290  2019-05-13 13:28:33.602314   
1597  zoo_sec01_01597  2019-05-13 13:29:12.578989  2019-05-13 13:31:12.689784   
1598  zoo_sec01_01598  2019-05-13 13:31:50.365057  2019-05-13 13:33:50.475290   
1599  zoo_sec01_01599  2019-05-13 13:34:28.814379  2019-05-13 13:36:28.934437   

      metric__mp.input.vdu01.0__stat__data__rx_bytes  \
0                                             1038.0   
1                                             1038.0   
2                                             1038.0   
3                                             1038.0   
4                                             1038.0   
...                                              ...   
1595                                          1038.0   
1596                                          1038.0   
1597                                           878.0   
1598                                          1038.0   
1599                                          1038.0   

      metric__mp.input.vdu01.0__stat__data__rx_packets  \
0                                                 13.0   
1                                                 13.0   
2                                                 13.0   
3                                                 13.0   
4                                                 13.0   
...                                                ...   
1595                                              13.0   
1596                                              13.0   
1597                                              11.0   
1598                                              13.0   
1599                                              13.0   

      metric__mp.input.vdu01.0__stat__data__tx_bytes  \
0                                       1.951180e+10   
1                                       1.971107e+10   
2                                       1.971275e+10   
3                                       1.955216e+10   
4                                       1.953329e+10   
...                                              ...   
1595                                    1.226542e+10   
1596                                    1.224587e+10   
1597                                    1.224242e+10   
1598                                    1.219213e+10   
1599                                    1.222880e+10   

      metric__mp.input.vdu01.0__stat__data__tx_packets  \
0                                           30191367.0   
1                                           30499563.0   
2                                           30502257.0   
3                                           30253611.0   
4                                           30224428.0   
...                                                ...   
1595                                        27317803.0   
1596                                        27276143.0   
1597                                        27266891.0   
1598                                        27157602.0   
1599                                        27239351.0   

      metric__mp.input.vdu01.0__stat__eth0__rx_bytes  \
0                                              764.0   
1                                              764.0   
2                                              648.0   
3                                              648.0   
4            

# Checking for any Null values in dataset


In [7]:
dataset_new = dataset_new.replace('', np.nan)
dataset_new.isnull().sum()

experiment_name                                     0
experiment_start                                    0
experiment_stop                                     0
metric__mp.input.vdu01.0__stat__data__rx_bytes      0
metric__mp.input.vdu01.0__stat__data__rx_packets    0
                                                   ..
param__mp__mp.input__name                           0
param__mp__mp.output__address                       0
param__mp__mp.output__connection_point              0
param__mp__mp.output__container                     0
param__mp__mp.output__name                          0
Length: 98, dtype: int64

In [8]:
dataset_new = dataset_new.dropna(axis=1, how='all')
dataset_new.isnull().sum()

experiment_name                                     0
experiment_start                                    0
experiment_stop                                     0
metric__mp.input.vdu01.0__stat__data__rx_bytes      0
metric__mp.input.vdu01.0__stat__data__rx_packets    0
                                                   ..
param__mp__mp.input__name                           0
param__mp__mp.output__address                       0
param__mp__mp.output__connection_point              0
param__mp__mp.output__container                     0
param__mp__mp.output__name                          0
Length: 87, dtype: int64

In [9]:
dataset_new

experiment_name            experiment_start             experiment_stop  \
0     zoo_sec01_00000  2019-05-10 14:34:58.787669  2019-05-10 14:36:58.909504   
1     zoo_sec01_00001  2019-05-10 14:37:45.155444  2019-05-10 14:39:45.276561   
2     zoo_sec01_00002  2019-05-10 14:40:30.377193  2019-05-10 14:42:30.487209   
3     zoo_sec01_00003  2019-05-10 14:43:15.109071  2019-05-10 14:45:15.230211   
4     zoo_sec01_00004  2019-05-10 14:45:59.170184  2019-05-10 14:47:59.291305   
...               ...                         ...                         ...   
1595  zoo_sec01_01595  2019-05-13 13:23:55.992925  2019-05-13 13:25:56.110507   
1596  zoo_sec01_01596  2019-05-13 13:26:33.492290  2019-05-13 13:28:33.602314   
1597  zoo_sec01_01597  2019-05-13 13:29:12.578989  2019-05-13 13:31:12.689784   
1598  zoo_sec01_01598  2019-05-13 13:31:50.365057  2019-05-13 13:33:50.475290   
1599  zoo_sec01_01599  2019-05-13 13:34:28.814379  2019-05-13 13:36:28.934437   

      metric__mp.input.vdu01.0__stat__data__rx_bytes  \
0                                             1038.0   
1                                             1038.0   
2                                             1038.0   
3                                             1038.0   
4                                             1038.0   
...                                              ...   
1595                                          1038.0   
1596                                          1038.0   
1597                                           878.0   
1598                                          1038.0   
1599                                          1038.0   

      metric__mp.input.vdu01.0__stat__data__rx_packets  \
0                                                 13.0   
1                                                 13.0   
2                                                 13.0   
3                                                 13.0   
4                                                 13.0   
...                                                ...   
1595                                              13.0   
1596                                              13.0   
1597                                              11.0   
1598                                              13.0   
1599                                              13.0   

      metric__mp.input.vdu01.0__stat__data__tx_bytes  \
0                                       1.951180e+10   
1                                       1.971107e+10   
2                                       1.971275e+10   
3                                       1.955216e+10   
4                                       1.953329e+10   
...                                              ...   
1595                                    1.226542e+10   
1596                                    1.224587e+10   
1597                                    1.224242e+10   
1598                                    1.219213e+10   
1599                                    1.222880e+10   

      metric__mp.input.vdu01.0__stat__data__tx_packets  \
0                                           30191367.0   
1                                           30499563.0   
2                                           30502257.0   
3                                           30253611.0   
4                                           30224428.0   
...                                                ...   
1595                                        27317803.0   
1596                                        27276143.0   
1597                                        27266891.0   
1598                                        27157602.0   
1599                                        27239351.0   

      metric__mp.input.vdu01.0__stat__eth0__rx_bytes  \
0                                              764.0   
1                                              764.0   
2                                              648.0   
3                                              648.0   
4            

In [10]:
def all_values_same(column):
    return column.nunique() == 1

columns_to_drop = dataset_new.columns[dataset_new.apply(all_values_same)]
dataset_new = dataset_new.drop(columns_to_drop, axis=1)

In [11]:
dataset_new

experiment_name            experiment_start             experiment_stop  \
0     zoo_sec01_00000  2019-05-10 14:34:58.787669  2019-05-10 14:36:58.909504   
1     zoo_sec01_00001  2019-05-10 14:37:45.155444  2019-05-10 14:39:45.276561   
2     zoo_sec01_00002  2019-05-10 14:40:30.377193  2019-05-10 14:42:30.487209   
3     zoo_sec01_00003  2019-05-10 14:43:15.109071  2019-05-10 14:45:15.230211   
4     zoo_sec01_00004  2019-05-10 14:45:59.170184  2019-05-10 14:47:59.291305   
...               ...                         ...                         ...   
1595  zoo_sec01_01595  2019-05-13 13:23:55.992925  2019-05-13 13:25:56.110507   
1596  zoo_sec01_01596  2019-05-13 13:26:33.492290  2019-05-13 13:28:33.602314   
1597  zoo_sec01_01597  2019-05-13 13:29:12.578989  2019-05-13 13:31:12.689784   
1598  zoo_sec01_01598  2019-05-13 13:31:50.365057  2019-05-13 13:33:50.475290   
1599  zoo_sec01_01599  2019-05-13 13:34:28.814379  2019-05-13 13:36:28.934437   

      metric__mp.input.vdu01.0__stat__data__rx_bytes  \
0                                             1038.0   
1                                             1038.0   
2                                             1038.0   
3                                             1038.0   
4                                             1038.0   
...                                              ...   
1595                                          1038.0   
1596                                          1038.0   
1597                                           878.0   
1598                                          1038.0   
1599                                          1038.0   

      metric__mp.input.vdu01.0__stat__data__rx_packets  \
0                                                 13.0   
1                                                 13.0   
2                                                 13.0   
3                                                 13.0   
4                                                 13.0   
...                                                ...   
1595                                              13.0   
1596                                              13.0   
1597                                              11.0   
1598                                              13.0   
1599                                              13.0   

      metric__mp.input.vdu01.0__stat__data__tx_bytes  \
0                                       1.951180e+10   
1                                       1.971107e+10   
2                                       1.971275e+10   
3                                       1.955216e+10   
4                                       1.953329e+10   
...                                              ...   
1595                                    1.226542e+10   
1596                                    1.224587e+10   
1597                                    1.224242e+10   
1598                                    1.219213e+10   
1599                                    1.222880e+10   

      metric__mp.input.vdu01.0__stat__data__tx_packets  \
0                                           30191367.0   
1                                           30499563.0   
2                                           30502257.0   
3                                           30253611.0   
4                                           30224428.0   
...                                                ...   
1595                                        27317803.0   
1596                                        27276143.0   
1597                                        27266891.0   
1598                                        27157602.0   
1599                                        27239351.0   

      metric__mp.input.vdu01.0__stat__eth0__rx_bytes  \
0                                              764.0   
1                                              764.0   
2                                              648.0   
3                                              648.0   
4            

In [12]:
dataset_new.columns

Index(['experiment_name', 'experiment_start', 'experiment_stop',
       'metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__rx_bytes',
       'metric__mp.output.vdu01.0__stat__data__rx_packets',
       'metric__mp.output.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.output.vdu01.0__stat__eth0__rx_packets',
       'metric__vnf0.vdu01.0__stat__br0__rx_bytes',
       'metric__vnf0.vdu01.0__stat__br0__rx_packets',
       'metric__vnf0.vdu01.0__stat__eth0__rx_bytes',
       'metric__vnf0.vdu01.0__stat__eth0__rx_packets',
       'metric__vnf0.vdu01.0__stat__eth0__tx_bytes',
       'metric__vnf0.vdu01.0__stat__eth0__tx_packets',
       'metric__vnf0.vdu01.0_

In [13]:
dataset_new = dataset_new.drop(['experiment_name', 'experiment_start', 'experiment_stop', 'metric__vnf0.vdu01.0__suricata_eve_timestamp', 'param__func__de.upb.ids-suricata.0.1__cmd_start', 'param__func__mp.input__cmd_start'],axis=1)
dataset_new.columns

Index(['metric__mp.input.vdu01.0__stat__data__rx_bytes',
       'metric__mp.input.vdu01.0__stat__data__rx_packets',
       'metric__mp.input.vdu01.0__stat__data__tx_bytes',
       'metric__mp.input.vdu01.0__stat__data__tx_packets',
       'metric__mp.input.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.input.vdu01.0__stat__eth0__rx_packets',
       'metric__mp.output.vdu01.0__stat__data__rx_bytes',
       'metric__mp.output.vdu01.0__stat__data__rx_packets',
       'metric__mp.output.vdu01.0__stat__eth0__rx_bytes',
       'metric__mp.output.vdu01.0__stat__eth0__rx_packets',
       'metric__vnf0.vdu01.0__stat__br0__rx_bytes',
       'metric__vnf0.vdu01.0__stat__br0__rx_packets',
       'metric__vnf0.vdu01.0__stat__eth0__rx_bytes',
       'metric__vnf0.vdu01.0__stat__eth0__rx_packets',
       'metric__vnf0.vdu01.0__stat__eth0__tx_bytes',
       'metric__vnf0.vdu01.0__stat__eth0__tx_packets',
       'metric__vnf0.vdu01.0__stat__input__rx_bytes',
       'metric__vnf0.vdu01.0__stat__inpu

In [14]:
dataset_new.dtypes

metric__mp.input.vdu01.0__stat__data__rx_bytes                        float64
metric__mp.input.vdu01.0__stat__data__rx_packets                      float64
metric__mp.input.vdu01.0__stat__data__tx_bytes                        float64
metric__mp.input.vdu01.0__stat__data__tx_packets                      float64
metric__mp.input.vdu01.0__stat__eth0__rx_bytes                        float64
metric__mp.input.vdu01.0__stat__eth0__rx_packets                      float64
metric__mp.output.vdu01.0__stat__data__rx_bytes                       float64
metric__mp.output.vdu01.0__stat__data__rx_packets                     float64
metric__mp.output.vdu01.0__stat__eth0__rx_bytes                       float64
metric__mp.output.vdu01.0__stat__eth0__rx_packets                     float64
metric__vnf0.vdu01.0__stat__br0__rx_bytes                             float64
metric__vnf0.vdu01.0__stat__br0__rx_packets                           float64
metric__vnf0.vdu01.0__stat__eth0__rx_bytes                      

In [15]:
X = dataset_new.iloc[:, :-2].values
y = dataset_new.iloc[:, -2:].values

In [16]:
print(X)

[[1.03800000e+03 1.30000000e+01 1.95117960e+10 ... 5.46810000e+04
  1.29000000e+02 4.13000000e+04]
 [1.03800000e+03 1.30000000e+01 1.97110659e+10 ... 5.99920000e+04
  1.28000000e+02 4.76000000e+04]
 [1.03800000e+03 1.30000000e+01 1.97127531e+10 ... 5.52380000e+04
  1.27000000e+02 4.13700000e+04]
 ...
 [8.78000000e+02 1.10000000e+01 1.22424226e+10 ... 1.81516000e+05
  1.41000000e+02 2.71168000e+05]
 [1.03800000e+03 1.30000000e+01 1.21921306e+10 ... 1.79848000e+05
  1.41000000e+02 2.71895000e+05]
 [1.03800000e+03 1.30000000e+01 1.22288032e+10 ... 1.84047000e+05
  1.41000000e+02 2.77893500e+05]]


In [17]:
print(y[:,1])
y[:, 1] = np.where(y[:, 1] == 256, 0, 1)
print(y[:, 1])

[ 256.  256.  256. ... 1024. 1024. 1024.]
[0. 0. 0. ... 1. 1. 1.]


## Splitting the dataset into the Training set and Test set

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Separate the two output features
y_train_output1 = y_train[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_train_output2 = y_train[:, 1]  # Second column for binary classification

y_test_output1 = y_test[:, 0]  # First column for the output ranging from 0.1 to 1.0
y_test_output2 = y_test[:, 1]  # Second column for binary classification

In [19]:
print(y_train_output2)

[0. 1. 0. ... 0. 1. 1.]


## Feature Scaling

In [20]:
from sklearn.preprocessing import MinMaxScaler

# Normalize input features
scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_test_normalized = scaler.transform(X_test)



In [21]:
print(X_train_normalized)

[[0.73529412 0.75       0.45478529 ... 0.98648359 0.97938144 0.91054082]
 [0.73529412 0.75       0.86096101 ... 0.0845404  0.79381443 0.1037392 ]
 [0.73529412 0.75       0.47162192 ... 0.89946635 0.98969072 0.82573226]
 ...
 [0.73529412 0.75       0.79050402 ... 0.38146664 0.88659794 0.36301662]
 [0.73529412 0.75       0.12963998 ... 0.2348721  0.98969072 0.38646733]
 [0.73529412 0.75       0.50770292 ... 0.9120144  0.97938144 0.96069202]]


In [22]:
print(type(y_train_output1))
print(type(y_train_output2))
print(type(y_test_output1))
print(type(y_test_output2))


# y_train_output1 = np.array(y_train_output1)
# y_train_output2 = np.array(y_train_output2)
# y_test_output1 = np.array(y_test_output1)
# y_test_output2 = np.array(y_test_output2)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
print(X_train_normalized.shape)
print(y_train_output1.shape)
print(y_train_output2.shape)
print(y_test_output1.shape)
print(y_test_output2.shape)

(1280, 55)
(1280,)
(1280,)
(320,)
(320,)


## Building Model

In [25]:
input_shape = (55,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=64, activation='relu')(inputs)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=64, activation='relu')(x)
x = tf.keras.layers.Dense(units=32, activation='relu')(x)
output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2])

# Check the model output names
print("Model Output Names:", model.output_names)  


Model Output Names: ['output_1', 'output_2']


In [26]:
model.compile(
    loss={
        'output_1': 'mean_squared_error',  # Regression loss function
        'output_2': 'binary_crossentropy'  # Binary classification loss function
    },
    optimizer='adam',
    metrics={
        'output_1': ['mae', 'mse'],
        'output_2': 'accuracy'
    }
)

model.fit(X_train_normalized, {'output_1': y_train_output1, 'output_2': y_train_output2},
          validation_data=(X_test_normalized, {'output_1': y_test_output1, 'output_2': y_test_output2}),
          epochs=50, batch_size=32)



Epoch 1/50
40/40 [==============================] - 4s 22ms/step - loss: 0.7950 - output_1_loss: 0.0961 - output_2_loss: 0.6989 - output_1_mae: 0.2334 - output_1_mse: 0.0961 - output_2_accuracy: 0.4688 - val_loss: 0.7031 - val_output_1_loss: 0.0121 - val_output_2_loss: 0.6910 - val_output_1_mae: 0.0944 - val_output_1_mse: 0.0121 - val_output_2_accuracy: 0.5094
Epoch 2/50
40/40 [==============================] - 0s 7ms/step - loss: 0.7191 - output_1_loss: 0.0220 - output_2_loss: 0.6971 - output_1_mae: 0.1189 - output_1_mse: 0.0220 - output_2_accuracy: 0.4805 - val_loss: 0.7015 - val_output_1_loss: 0.0089 - val_output_2_loss: 0.6927 - val_output_1_mae: 0.0771 - val_output_1_mse: 0.0089 - val_output_2_accuracy: 0.4906
Epoch 3/50
40/40 [==============================] - 0s 6ms/step - loss: 0.7090 - output_1_loss: 0.0161 - output_2_loss: 0.6930 - output_1_mae: 0.0997 - output_1_mse: 0.0161 - output_2_accuracy: 0.5109 - val_loss: 0.7090 - val_output_1_loss: 0.0111 - val_output_2_loss: 0.6979

Epoch 24/50
40/40 [==============================] - 0s 6ms/step - loss: 0.6937 - output_1_loss: 0.0044 - output_2_loss: 0.6894 - output_1_mae: 0.0508 - output_1_mse: 0.0044 - output_2_accuracy: 0.5219 - val_loss: 0.7045 - val_output_1_loss: 0.0060 - val_output_2_loss: 0.6985 - val_output_1_mae: 0.0587 - val_output_1_mse: 0.0060 - val_output_2_accuracy: 0.4812
Epoch 25/50
40/40 [==============================] - 0s 6ms/step - loss: 0.6920 - output_1_loss: 0.0044 - output_2_loss: 0.6876 - output_1_mae: 0.0509 - output_1_mse: 0.0044 - output_2_accuracy: 0.5484 - val_loss: 0.7042 - val_output_1_loss: 0.0073 - val_output_2_loss: 0.6969 - val_output_1_mae: 0.0683 - val_output_1_mse: 0.0073 - val_output_2_accuracy: 0.4844
Epoch 26/50
40/40 [==============================] - 0s 6ms/step - loss: 0.6943 - output_1_loss: 0.0044 - output_2_loss: 0.6899 - output_1_mae: 0.0513 - output_1_mse: 0.0044 - output_2_accuracy: 0.5375 - val_loss: 0.7011 - val_output_1_loss: 0.0050 - val_output_2_loss: 0.69

Epoch 47/50
40/40 [==============================] - 0s 6ms/step - loss: 0.6698 - output_1_loss: 0.0044 - output_2_loss: 0.6654 - output_1_mae: 0.0509 - output_1_mse: 0.0044 - output_2_accuracy: 0.5672 - val_loss: 0.6652 - val_output_1_loss: 0.0032 - val_output_2_loss: 0.6620 - val_output_1_mae: 0.0425 - val_output_1_mse: 0.0032 - val_output_2_accuracy: 0.5344
Epoch 48/50
40/40 [==============================] - 0s 6ms/step - loss: 0.6717 - output_1_loss: 0.0048 - output_2_loss: 0.6669 - output_1_mae: 0.0534 - output_1_mse: 0.0048 - output_2_accuracy: 0.5594 - val_loss: 0.6607 - val_output_1_loss: 0.0052 - val_output_2_loss: 0.6555 - val_output_1_mae: 0.0540 - val_output_1_mse: 0.0052 - val_output_2_accuracy: 0.5437
Epoch 49/50
40/40 [==============================] - 0s 6ms/step - loss: 0.6634 - output_1_loss: 0.0042 - output_2_loss: 0.6592 - output_1_mae: 0.0494 - output_1_mse: 0.0042 - output_2_accuracy: 0.5836 - val_loss: 0.6633 - val_output_1_loss: 0.0039 - val_output_2_loss: 0.65

In [27]:
# Predict on the test data
y_pred_output1, y_pred_output2 = model.predict(X_test_normalized)

# For output_1 (Regression)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_output1 = mean_absolute_error(y_test_output1, y_pred_output1)
mse_output1 = mean_squared_error(y_test_output1, y_pred_output1)
r2_output1 = r2_score(y_test_output1, y_pred_output1)

print("Output 1 - Mean Absolute Error:", mae_output1)
print("Output 1 - Mean Squared Error:", mse_output1)
print("Output 1 - R^2 Score:", r2_output1)



# For output_2 (Classification)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Convert probabilities to binary predictions (0 or 1) for classification
y_pred_output2_binary = (y_pred_output2 > 0.5).astype(int)

accuracy_output2 = accuracy_score(y_test_output2, y_pred_output2_binary)
conf_matrix_output2 = confusion_matrix(y_test_output2, y_pred_output2_binary)
classification_rep_output2 = classification_report(y_test_output2, y_pred_output2_binary)

print("Output 2 - Accuracy:", accuracy_output2)
print("Output 2 - Confusion Matrix:")
print(conf_matrix_output2)
print("Output 2 - Classification Report:")
print(classification_rep_output2)


10/10 [==============================] - 0s 3ms/step
Output 1 - Mean Absolute Error: 0.04874033238273114
Output 1 - Mean Squared Error: 0.003989782359040421
Output 1 - R^2 Score: 0.9511036772661706
Output 2 - Accuracy: 0.553125
Output 2 - Confusion Matrix:
[[ 76  89]
 [ 54 101]]
Output 2 - Classification Report:
              precision    recall  f1-score   support

         0.0       0.58      0.46      0.52       165
         1.0       0.53      0.65      0.59       155

    accuracy                           0.55       320
   macro avg       0.56      0.56      0.55       320
weighted avg       0.56      0.55      0.55       320



In [28]:
y_test1 = y_test[:,0]

rounded_y_pred = y_pred_output1.reshape(len(y_pred_output1), 1).round(1)

# Reshape y_test1 to a column vector
y_test1_reshaped = y_test1.reshape(len(y_test1), 1)

# Concatenate both arrays side by side (along axis 1)
result = np.concatenate((rounded_y_pred, y_test1_reshaped), axis=1)
np.set_printoptions(precision=1)
print(result)

[[0.4 0.4]
 [0.6 0.5]
 [0.9 1. ]
 [0.2 0.2]
 [0.2 0.3]
 [0.6 0.6]
 [0.3 0.3]
 [0.9 1. ]
 [0.8 0.8]
 [0.2 0.1]
 [0.7 0.8]
 [0.8 0.9]
 [1.  1. ]
 [0.1 0.1]
 [0.4 0.4]
 [0.2 0.2]
 [0.4 0.4]
 [0.3 0.3]
 [0.8 0.8]
 [0.2 0.2]
 [0.1 0.1]
 [0.1 0.1]
 [0.5 0.5]
 [0.5 0.5]
 [0.3 0.3]
 [0.6 0.7]
 [0.4 0.4]
 [0.3 0.3]
 [0.9 1. ]
 [0.7 0.7]
 [0.7 0.8]
 [0.6 0.6]
 [0.4 0.4]
 [0.4 0.4]
 [0.7 0.8]
 [0.4 0.4]
 [1.  1. ]
 [0.8 0.8]
 [0.4 0.5]
 [0.2 0.2]
 [0.8 1. ]
 [0.6 0.6]
 [0.6 0.6]
 [0.7 0.7]
 [0.5 0.5]
 [0.7 0.8]
 [0.8 0.9]
 [0.7 0.7]
 [0.9 1. ]
 [0.6 0.6]
 [0.3 0.3]
 [0.5 0.6]
 [0.6 0.6]
 [0.1 0.1]
 [0.2 0.3]
 [0.9 1. ]
 [0.7 0.7]
 [0.7 0.7]
 [0.2 0.2]
 [0.8 0.9]
 [0.2 0.2]
 [0.7 0.7]
 [0.7 0.7]
 [0.8 1. ]
 [0.1 0.1]
 [0.1 0.1]
 [0.8 1. ]
 [0.9 1. ]
 [0.8 0.9]
 [0.7 0.7]
 [0.8 0.9]
 [0.4 0.4]
 [0.2 0.1]
 [0.5 0.5]
 [0.2 0.1]
 [0.9 1. ]
 [0.8 0.8]
 [0.5 0.4]
 [0.9 0.9]
 [0.2 0.1]
 [0.6 0.6]
 [0.5 0.5]
 [0.1 0.1]
 [0.3 0.3]
 [0.5 0.6]
 [0.6 0.5]
 [0.4 0.4]
 [0.7 0.7]
 [0.9 1. ]
 [0.1 0.1]
 [0.5 0.6]

## K-fold Cross Validation

In [29]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


def gelu_activation(x):
    return 0.5 * x * (1 + tf.keras.activations.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * tf.keras.backend.pow(x, 3))))



num_folds = 5

# Initialize lists to store the evaluation metrics for each fold
mse_output1_list = []
accuracy_output2_list = []

# Create the KFold object
kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)


# Create the model
input_shape = (55,)
inputs = tf.keras.Input(shape=input_shape)
x = tf.keras.layers.Dense(units=256, activation=gelu_activation)(inputs)  # GELU activation
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=256, activation=gelu_activation)(x)  # GELU activation
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=256, activation=gelu_activation)(x)  # GELU activation
x = tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Dropout(0.2)(x)
x = tf.keras.layers.Dense(units=128, activation=gelu_activation)(x)  # GELU activation
   

output_1 = tf.keras.layers.Dense(units=1, activation='linear', name='output_1')(x)  # Output 1: Regression
output_2 = tf.keras.layers.Dense(units=1, activation='sigmoid', name='output_2')(x)  # Output 2: Classification

model = tf.keras.Model(inputs=inputs, outputs=[output_1, output_2])

# Perform 5-fold cross-validation
for fold, (train_indices, val_indices) in enumerate(kfold.split(X_train_normalized)):
    print(f"Fold {fold+1}/{num_folds}")
    
    # Split the data into training and validation sets for this fold
    X_train_fold = X_train_normalized[train_indices]
    X_val_fold = X_train_normalized[val_indices]
    y_train_output1_fold = y_train_output1[train_indices]
    y_train_output2_fold = y_train_output2[train_indices]
    y_val_output1_fold = y_train_output1[val_indices]
    y_val_output2_fold = y_train_output2[val_indices]
    
    
    # Compile the model
    model.compile(
        loss={
            'output_1': 'mean_squared_error',  # Regression loss function
            'output_2': 'binary_crossentropy'  # Binary classification loss function
        },
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        metrics={
            'output_1': ['mae', 'mse'],
            'output_2': 'accuracy'
        }
    )
    

    # Train the model
    model.fit(X_train_fold, {'output_1': y_train_output1_fold, 'output_2': y_train_output2_fold},
          epochs=150, batch_size=128, verbose=0)

    
    # Evaluate the model on validation data for this fold
    results = model.evaluate(X_val_fold, {'output_1': y_val_output1_fold, 'output_2': y_val_output2_fold})
    
    mse_output1_list.append(results[2])  # Index 2 corresponds to MSE for 'output_1'
    accuracy_output2_list.append(results[5])  # Index 5 corresponds to accuracy for 'output_2'



Fold 1/5
8/8 [==============================] - 1s 6ms/step - loss: 0.7565 - output_1_loss: 0.0075 - output_2_loss: 0.7491 - output_1_mae: 0.0632 - output_1_mse: 0.0075 - output_2_accuracy: 0.6680
Fold 2/5
8/8 [==============================] - 1s 6ms/step - loss: 0.9368 - output_1_loss: 0.0031 - output_2_loss: 0.9337 - output_1_mae: 0.0429 - output_1_mse: 0.0031 - output_2_accuracy: 0.6484
Fold 3/5
8/8 [==============================] - 1s 5ms/step - loss: 0.7176 - output_1_loss: 0.0018 - output_2_loss: 0.7158 - output_1_mae: 0.0342 - output_1_mse: 0.0018 - output_2_accuracy: 0.7773
Fold 4/5
8/8 [==============================] - 1s 5ms/step - loss: 0.7650 - output_1_loss: 0.0024 - output_2_loss: 0.7626 - output_1_mae: 0.0381 - output_1_mse: 0.0024 - output_2_accuracy: 0.7656
Fold 5/5
8/8 [==============================] - 1s 5ms/step - loss: 0.3561 - output_1_loss: 0.0020 - output_2_loss: 0.3541 - output_1_mae: 0.0339 - output_1_mse: 0.0020 - output_2_accuracy: 0.8750


In [30]:
# Calculate the mean and standard deviation of evaluation metrics across all folds
mean_mse_output1 = np.mean(mse_output1_list)
mean_accuracy_output2 = np.mean(accuracy_output2_list)

std_mse_output1 = np.std(mse_output1_list)
std_accuracy_output2 = np.std(accuracy_output2_list)

# For regression task (output_1) - Calculate R-squared (R^2) score
y_true_output1 = np.concatenate([y_train_output1, y_test_output1])
y_pred_output1 = model.predict(np.concatenate([X_train_normalized, X_test_normalized]))[0]
r2_output1 = r2_score(y_true_output1, y_pred_output1)

print("Mean MSE (Output 1):", mean_mse_output1)
print("Mean Accuracy (Output 2):", mean_accuracy_output2)

print("Standard Deviation MSE (Output 1):", std_mse_output1)
print("Standard Deviation Accuracy (Output 2):", std_accuracy_output2)

print("R^2 Score (Output 1 - Regression):", r2_output1)


50/50 [==============================] - 1s 4ms/step
Mean MSE (Output 1): 0.7030624389648438
Mean Accuracy (Output 2): 0.746875
Standard Deviation MSE (Output 1): 0.19016348000980487
Standard Deviation Accuracy (Output 2): 0.08199031716840105
R^2 Score (Output 1 - Regression): 0.9817774468292974


In [31]:
# 1. Compare Regression Output with Original Test Values

# Predict using the trained model on the test data for the regression output (output_1)
y_pred_output1_test = model.predict(X_test_normalized)[0]

# Reshape the predictions and original test values to match for comparison
y_pred_output1_test = y_pred_output1_test.flatten()

# Convert both arrays to the same data type (e.g., float64) for comparison
y_test_output1 = y_test_output1.astype(np.float64)
y_pred_output1_test = y_pred_output1_test.astype(np.float64)

# Stack the original test values and predicted values horizontally
comparison_output1 = np.column_stack((y_test_output1, y_pred_output1_test))

# Print the original test values and predicted values side by side
print("Original Test Values (Output 1) vs. Predicted Values (Output 1):")
print(comparison_output1)

10/10 [==============================] - 0s 4ms/step
Original Test Values (Output 1) vs. Predicted Values (Output 1):
[[0.4 0.3]
 [0.5 0.5]
 [1.  0.9]
 [0.2 0.2]
 [0.3 0.3]
 [0.6 0.6]
 [0.3 0.3]
 [1.  1. ]
 [0.8 0.8]
 [0.1 0.2]
 [0.8 0.8]
 [0.9 0.9]
 [1.  1. ]
 [0.1 0.1]
 [0.4 0.4]
 [0.2 0.2]
 [0.4 0.4]
 [0.3 0.3]
 [0.8 0.8]
 [0.2 0.2]
 [0.1 0.1]
 [0.1 0.1]
 [0.5 0.5]
 [0.5 0.5]
 [0.3 0.3]
 [0.7 0.6]
 [0.4 0.4]
 [0.3 0.3]
 [1.  1. ]
 [0.7 0.7]
 [0.8 0.8]
 [0.6 0.7]
 [0.4 0.4]
 [0.4 0.3]
 [0.8 0.9]
 [0.4 0.4]
 [1.  1. ]
 [0.8 0.8]
 [0.5 0.5]
 [0.2 0.2]
 [1.  0.9]
 [0.6 0.6]
 [0.6 0.6]
 [0.7 0.7]
 [0.5 0.4]
 [0.8 0.8]
 [0.9 0.9]
 [0.7 0.6]
 [1.  1. ]
 [0.6 0.6]
 [0.3 0.3]
 [0.6 0.6]
 [0.6 0.6]
 [0.1 0.1]
 [0.3 0.4]
 [1.  1.1]
 [0.7 0.7]
 [0.7 0.7]
 [0.2 0.2]
 [0.9 0.9]
 [0.2 0.2]
 [0.7 0.8]
 [0.7 0.7]
 [1.  0.9]
 [0.1 0.1]
 [0.1 0.1]
 [1.  0.9]
 [1.  1. ]
 [0.9 0.9]
 [0.7 0.7]
 [0.9 0.9]
 [0.4 0.4]
 [0.1 0.1]
 [0.5 0.6]
 [0.1 0.1]
 [1.  1. ]
 [0.8 0.9]
 [0.4 0.4]
 [0.9 1. ]
 [0.1 0.1]
 [

In [33]:
# 2. Generate Confusion Matrix for Classification

# Predict using the trained model on the test data for the classification output (output_2)
y_pred_output2_test = model.predict(X_test_normalized)[1]

# Convert the probability predictions to binary class labels (0 or 1)
y_pred_output2_test_binary = np.round(y_pred_output2_test).astype(int).flatten()

# Import the confusion_matrix function from sklearn.metrics
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
conf_matrix_output2 = confusion_matrix(y_test_output2, y_pred_output2_test_binary)

# Print the confusion matrix
print("Confusion Matrix (Output 2 - Classification):")
print(conf_matrix_output2)

10/10 [==============================] - 0s 4ms/step
Confusion Matrix (Output 2 - Classification):
[[106  59]
 [ 48 107]]
